declare @num_doc int = 785 

SELECT TOP (1000) [id]
      ,[id_document]
      ,[num]
      ,[id_outgoing]
      ,[id_car]
      ,[id_condition]
      ,[id_wagons_rent_arrival]
      ,[id_wagons_rent_outgoing]
      ,[id_countrys]
      ,[id_genus]
      ,[id_owner]
      ,[gruzp_uz]
      ,[tara_uz]
      ,[note_uz]
      ,[gruzp]
      ,[u_tara]
      ,[ves_tary_arc]
      ,[id_warehouse]
      ,[id_division]
      ,[laden]
      ,[id_cargo]
      ,[id_cargo_gng]
      ,[vesg]
      ,[code_stn_to]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon]
  where [id] in (select [id_outgoing_uz_vagon] FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars] where [position_outgoing] is not null and [id_outgoing] = (select top(1) [id] FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingSostav] where [num_doc] = @num_doc  order by 1 desc))

SELECT TOP (1000) [id]
      ,[id_doc_uz]
      ,[nom_doc]
      ,[code_stn_from]
      ,[code_stn_to]
      ,[country_nazn]
      ,[code_border_checkpoint]
      ,[cross_date]
      ,[code_shipper]
      ,[code_consignee]
      ,[vid]
      ,[code_payer]
      ,[distance_way]
      ,[osum]
      ,[date_sozdan]
      ,[date_otpr]
      ,[date_pr]
      ,[date_grpol]
      ,[date_vid]
      ,[info_sht]
      ,[name_gr]
      ,[note]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[tariff_contract]
      ,[calc_payer]
      ,[calc_payer_user]
      ,[num_list]
      ,[date_list]
      ,[Verification]
      ,[VerificationUser]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Document]
  where [id] in (select [id_document] FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon]
  where [id] in (select [id_outgoing_uz_vagon] FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars] where [position_outgoing] is not null and [id_outgoing] = (select top(1) [id] FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingSostav] where [num_doc] = @num_doc  order by 1 desc)) )
