/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT [id]
      ,[id_document]
      ,[num]
      ,[id_outgoing]
      ,[id_car]
      ,[id_condition]
      ,[id_wagons_rent_arrival]
      ,[id_wagons_rent_outgoing]
      ,[id_countrys]
      ,[id_genus]
      ,[id_owner]
      ,[gruzp_uz]
      ,[tara_uz]
      ,[note_uz]
      ,[gruzp]
      ,[u_tara]
      ,[ves_tary_arc]
      ,[id_warehouse]
      ,[id_division]
      ,[laden]
      ,[id_cargo]
      ,[id_cargo_gng]
      ,[vesg]
      ,[code_stn_to]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon]
  --where [id_owner] = 0
  where [id_genus] = 0
  order by 1 desc

/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT TOP (1000) [num]
      ,[id_countrys]
      ,[id_genus]
      ,[id_owner]
      ,[id_operator]
      ,[change_operator]
      ,[gruzp]
      ,[tara]
      ,[kol_os]
      ,[usl_tip]
      ,[date_rem_uz]
      ,[date_rem_vag]
      ,[id_type_ownership]
      ,[sign]
      ,[factory_number]
      ,[inventory_number]
      ,[year_built]
      ,[exit_ban]
      ,[note]
      ,[sobstv_kis]
      ,[bit_warning]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[closed_route]
      ,[new_construction]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_Wagons]
  where [num] = 52637782
  /****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT TOP (1000) [id]
      ,[num]
      ,[id_operator]
      ,[id_limiting]
      ,[rent_start]
      ,[rent_end]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[parent_id]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_WagonsRent]
  where [num] = 52637782
