/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
declare @id_car bigint = 238731--233740--14306 //

--select id_outgoing_uz_vagon FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars] where [id]=@id_car

select N'OUT CARS'
SELECT [id]
      ,[id_outgoing]
      ,[num]
      ,[position]
      ,[position_outgoing]
      ,[num_doc]
      ,[note]
      ,[date_outgoing_act]
      ,[outgoing]
      ,[outgoing_user]
      ,[id_outgoing_uz_vagon]
      ,[id_outgoing_detention]
      ,[id_reason_discrepancy_amkr]
      ,[id_reason_discrepancy_uz]
      ,[id_outgoing_return_start]
      ,[id_outgoing_return_stop]
      ,[parent_wir_id]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[note_vagonnik]
      ,[vagonnik]
      ,[vagonnik_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars]
  where [id]=@id_car


select N'ДОКУМЕНТ + PAY'
SELECT [id]
      ,[id_doc_uz]
      ,[nom_doc]
      ,[code_stn_from]
      ,[code_stn_to]
      ,[country_nazn]
      ,[code_border_checkpoint]
      ,[cross_date]
      ,[code_shipper]
      ,[code_consignee]
      ,[vid]
      ,[code_payer]
      ,[distance_way]
      ,[osum]
      ,[date_sozdan]
      ,[date_otpr]
      ,[date_pr]
      ,[date_grpol]
      ,[date_vid]
      ,[info_sht]
      ,[name_gr]
      ,[note]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Document]
  where [id] = (SELECT [id_document] FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon]  where id = (select id_outgoing_uz_vagon FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars] where [id]=@id_car))
/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT  [id]
      ,[id_document]
      ,[code_payer]
      ,[type_payer]
      ,[kod]
      ,[summa]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Document_Pay]
  where [id_document] = (SELECT [id_document] FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon]  where id = (select id_outgoing_uz_vagon FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars] where [id]=@id_car))

select N'ВАГОН'
SELECT [id]
      ,[id_document]
      ,[num]
      ,[id_outgoing]
      ,[id_car]
      ,[id_condition]
      ,[id_wagons_rent_arrival]
      ,[id_wagons_rent_outgoing]
      ,[id_countrys]
      ,[id_genus]
      ,[id_owner]
      ,[gruzp_uz]
      ,[tara_uz]
      ,[note_uz]
      ,[gruzp]
      ,[u_tara]
      ,[ves_tary_arc]
      ,[id_warehouse]
      ,[id_division]
      ,[laden]
      ,[id_cargo]
      ,[id_cargo_gng]
      ,[vesg]
      ,[code_stn_to]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon]  
  where id = (select id_outgoing_uz_vagon FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars] where [id]=@id_car)
select N'КОНТЕЙНЕРА + PAY'
SELECT TOP (1000) [id]
      ,[id_vagon]
      ,[nom_cont]
      ,[kod_tiporazmer]
      ,[gruzp]
      ,[ves_tary_arc]
      ,[id_cargo]
      ,[id_cargo_gng]
      ,[kol_pac]
      ,[pac]
      ,[vesg]
      ,[nom_zpu]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon_Cont]
  where [id_vagon]=(select id_outgoing_uz_vagon FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars] where [id]=@id_car)

SELECT [id]
      ,[id_cont]
      ,[kod]
      ,[summa]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Cont_Pay]
  where [id_cont] in (SELECT [id] FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon_Cont] where [id_vagon]=(select id_outgoing_uz_vagon FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars] where [id]=@id_car))
select N'ВАГОН АКТ'
SELECT [id]
      ,[id_vagon]
      ,[date_akt]
      ,[date_dved]
      ,[nom_akt]
      ,[nom_dved]
      ,[prichina_akt]
      ,[stn_akt]
      ,[stn_name_akt]
      ,[type]
      ,[vagon_nom]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon_Acts]
  where [id_vagon]=(select id_outgoing_uz_vagon FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars] where [id]=@id_car)
  select N'ВАГОН PAY'
  SELECT [id]
      ,[id_vagon]
      ,[kod]
      ,[summa]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon_Pay]
  where [id_vagon]=(select id_outgoing_uz_vagon FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars] where [id]=@id_car)

  SELECT [num_doc]
      ,[revision]
      ,[status]
      ,[code_from]
      ,[code_on]
      ,[dt]
      ,[xml_doc]
      ,[num_uz]
  FROM [KRR-PA-CNT-Railway].[IDS].[UZ_DOC_OUT]
  where [num_doc] = (select [num_doc] FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars] where [id]=@id_car)