SELECT [N_NATUR]
      ,[N_VED_PR]
      ,[N_SOST_OT]
      ,[N_SOST_PR]
      ,[POD_L]
      ,[POD_N]
      ,[K_ST]
      ,[K_ST_OTPR]
      ,[K_ST_PR]
      ,[N_PUT]
      ,[NAPR]
      ,[K_POLUCH]
      ,[D_PR_DD]
      ,[D_PR_MM]
      ,[D_PR_YY]
      ,[T_PR_HH]
      ,[T_PR_MI]
      ,[D_DD]
      ,[D_MM]
      ,[D_YY]
      ,[T_HH]
      ,[T_MI]
      ,[K_GR]
      ,[P_OT]
      ,[FIO_V_KMK]
      ,[FIO_V_MPS]
      ,[FIO_P_KMK]
      ,[FIO_P_MPS]
      ,[V_WSEGO]
      ,[V_MPS]
      ,[V_KMK]
      ,[WES]
      ,[V_KR]
      ,[V_P]
      ,[V_PV]
      ,[V_X]
      ,[V_C]
      ,[V_D]
      ,[V_CM]
      ,[V_PR]
      ,[V_G]
      ,[V_K]
      ,[V_CH]
      ,[V_S]
      ,[V_SS]
      ,[V_MR]
      ,[V_SH]
      ,[V_EX]
      ,[T_PRED_HH]
      ,[T_PRED_MI]
      ,[T_OGR_HH]
      ,[T_OGR_MI]
      ,[T_OBR_HH]
      ,[T_OBR_MI]
      ,[T_SOGR_HH]
      ,[T_SOGR_MI]
      ,[N_GOL]
      ,[N_HV]
      ,[K_SIGN]
      ,[ST_OTPR]
      ,[OTPRAV]
      ,[V_KR_KMK]
      ,[V_P_KMK]
      ,[V_PV_KMK]
      ,[V_X_KMK]
      ,[V_C_KMK]
      ,[V_D_KMK]
      ,[V_CM_KMK]
      ,[V_PR_KMK]
      ,[V_K_SNG]
      ,[V_CH_SNG]
      ,[V_SS_SNG]

      ,[MARSH]
      ,[DAT_VVOD]
      ,[DPA]
      ,[DSA]
      ,[R]
      ,[PAY]
  FROM [WAGONS]..[PROM].[SOSTAV]
  --where P_OT =1 and [N_NATUR] = 3259
  where P_OT =1 and [N_NATUR] = 3267

GO


