/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT TOP (1000) [id]
      ,[nom_doc]
      ,[nomer]
      ,[calc_weight]
      ,[etsng_old]
      ,[gng_old]
      ,[gruzp]
      ,[is_removed]
      ,[ostat_davl]
      ,[kod_adm]
      ,[kod_firm_owner]
      ,[kol_conductor]
      ,[kol_os]
      ,[measure_equip_num]
      ,[name_firm_owner]
      ,[negab_do]
      ,[negab_rs]
      ,[negab_v]
      ,[nom_ref]
      ,[pour_off_date]
      ,[pr_sobst]
      ,[pr_zam]
      ,[promoted_by]
      ,[remove_weight]
      ,[rod_vag]
      ,[roller_weight]
      ,[tank_state]
      ,[use]
      ,[usl_tip]
      ,[u_tara]
      ,[ves_tary_arc]
      ,[zd_kod]
      ,[dt]
      ,[flag_railway]
  FROM [KRR-PA-VIZ-Other_DATA].[dbo].[UZ_VagonData]
  where [nomer]='57925646'
  order by 1 desc

  SELECT TOP (1000) [id]
      ,[doc_Id]
      ,[doc_Revision]
      ,[doc_Status]
      ,[depart_code]
      ,[arrived_code]
      ,[dt]
      ,[update_dt]
      ,[raw_xml]
      ,[namespace_uri]
  FROM [KRR-PA-VIZ-Other_DATA].[dbo].[UZ_Data]
  where [doc_Id] in (select [nom_doc] FROM [KRR-PA-VIZ-Other_DATA].[dbo].[UZ_VagonData] where [nomer]='57925646')