SELECT TOP (1000) [id]
      ,[position]
      ,[name_division_ru]
      ,[name_division_en]
      ,[division_abbr_ru]
      ,[division_abbr_en]
      ,[id_type_devision]
      ,[code]
      ,[old]
      ,[parent_id]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_Divisions]
  order by [name_division_ru]

  SELECT TOP (1000) [id]
      ,[id_group]
      ,[id_cargo_etsng]
      ,[cargo_name_ru]
      ,[cargo_name_en]
      ,[code_sap]
      ,[empty_weight]
      ,[sending]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[id_out_group]
      ,[ban_change]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_Cargo]
  order by [cargo_name_ru]
