SELECT [id]
      ,[num_filing]
      ,[type_filing]
      ,[id_division]
      ,[vesg]
      ,[note]
      ,[start_filing]
      ,[end_filing]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[close]
      ,[close_user]
  FROM [KRR-PA-CNT-Railway-Archive].[IDS].[WagonFiling]

  SELECT TOP (1000) [id]
      ,[id_wagon_internal_routes]
      ,[id_station]
      ,[id_way]
      ,[way_start]
      ,[way_end]
      ,[id_outer_way]
      ,[outer_way_start]
      ,[outer_way_end]
      ,[position]
      ,[note]
      ,[create]
      ,[create_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
      ,[id_wio]
      ,[num_sostav]
      ,[filing_start]
      ,[filing_end]
      ,[id_filing]
  FROM [KRR-PA-CNT-Railway-Archive].[IDS].[WagonInternalMovement]
  where [id_filing] is not null

  SELECT TOP (1000) [id]
      ,[id_wagon_internal_routes]
      ,[id_operation]
      ,[operation_start]
      ,[operation_end]
      ,[id_condition]
      ,[id_loading_status]
      ,[locomotive1]
      ,[locomotive2]
      ,[note]
      ,[create]
      ,[create_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
      ,[con_change]
      ,[con_change_user]
	  --delete
  FROM [KRR-PA-CNT-Railway-Archive].[IDS].[WagonInternalOperation]
  where [id_operation] in (13,14, 15,16)