declare @id_sostav int = 200536
SELECT TOP (1000) [id]
      ,[num_doc]
      ,[id_station_from]
      ,[id_way_from]
      ,[id_station_on]
      ,[date_readiness_amkr]
      ,[date_end_inspection_acceptance_delivery]
      ,[date_end_inspection_loader]
      ,[date_end_inspection_vagonnik]
      ,[date_show_wagons]
      ,[date_readiness_uz]
      ,[date_outgoing]
      ,[date_outgoing_act]
      ,[date_departure_amkr]
      ,[composition_index]
      ,[status]
      ,[route_sign]
      ,[note]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[vagonnik_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingSostav]
  where id =@id_sostav

  /****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT TOP (1000) [id]
      ,[id_outgoing]
      ,[num]
      ,[position]
      ,[position_outgoing]
      ,[num_doc]
      ,[note]
      ,[date_outgoing_act]
      ,[outgoing]
      ,[outgoing_user]
      ,[id_outgoing_uz_vagon]
      ,[id_outgoing_detention]
      ,[id_reason_discrepancy_amkr]
      ,[id_reason_discrepancy_uz]
      ,[id_outgoing_return_start]
      ,[id_outgoing_return_stop]
      ,[parent_wir_id]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[note_vagonnik]
      ,[vagonnik]
      ,[vagonnik_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars]
  where [id_outgoing] =@id_sostav and  [position_outgoing] is not null

  /****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT TOP (1000) [id]
      ,[id_document]
      ,[num]
      ,[id_outgoing]
      ,[id_car]
      ,[id_condition]
      ,[id_wagons_rent_arrival]
      ,[id_wagons_rent_outgoing]
      ,[id_countrys]
      ,[id_genus]
      ,[id_owner]
      ,[gruzp_uz]
      ,[tara_uz]
      ,[note_uz]
      ,[gruzp]
      ,[u_tara]
      ,[ves_tary_arc]
      ,[id_warehouse]
      ,[id_division]
      ,[laden]
      ,[id_cargo]
      ,[id_cargo_gng]
      ,[vesg]
      ,[code_stn_to]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon]
  where [id] in (SELECT [id_outgoing_uz_vagon] FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars]  where [id_outgoing] =@id_sostav and  [position_outgoing] is not null)

  /****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT wr.[id]
      ,wr.[num]
      ,wr.[id_operator]
      ,wr.[id_limiting]
      ,wr.[rent_start]
      ,wr.[rent_end]
	  ,[date_outgoing] = (select [date_outgoing] FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingSostav] where id =@id_sostav)
      --,wr.[create]
      --,wr.[create_user]
      --,wr.[change]
      --,wr.[change_user]
      ,wr.[parent_id]
	  ,[id_outgoing_uz_vagon] = (SELECT [id_outgoing_uz_vagon] FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars]  where [id_outgoing] =@id_sostav and [num] = wr.[num])
	  ,[new_id] = (SELECT [id] FROM [KRR-PA-CNT-Railway].[IDS].[Directory_WagonsRent]
   where num = wr.[num] and [rent_start]<(select [date_outgoing] FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingSostav] where id =@id_sostav) 
   and ([rent_end] is null or  [rent_end] > (select [date_outgoing] FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingSostav] where id =@id_sostav)))
  --into change_rent_outgoing
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_WagonsRent] as wr
  where [id] in (SELECT [id_wagons_rent_outgoing] FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon] where [id] in (SELECT [id_outgoing_uz_vagon] FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars]  where [id_outgoing] =@id_sostav and  [position_outgoing] is not null))
  and [rent_end] < (select [date_outgoing] FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingSostav] where id =@id_sostav)

  /****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
