declare @id_cargo int = 26
SELECT TOP (1000) [id]
      ,[code]
      ,[cargo_etsng_name_ru]
      ,[cargo_etsng_name_en]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_CargoETSNG]
  where code=161147  

  /****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[id_group]
      ,[id_cargo_etsng]
      ,[cargo_name_ru]
      ,[cargo_name_en]
      ,[code_sap]
      ,[sending]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[id_out_group]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_Cargo]
  where [id_cargo_etsng]=21

SELECT TOP (1000) [id]
      ,[code]
      ,[cargo_gng_name_ru]
      ,[cargo_gng_name_en]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_CargoGNG]
  where [code]=27011210 

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[id_document]
      ,[num]
      ,[id_arrival]
      ,[id_car]
      ,[id_condition]
      ,[id_type]
      ,[gruzp]
      ,[u_tara]
      ,[ves_tary_arc]
      ,[route]
      ,[note_vagon]
      ,[id_cargo]
      ,[id_cargo_gng]
      ,[id_certification_data]
      ,[id_commercial_condition]
      ,[kol_pac]
      ,[pac]
      ,[vesg]
      ,[vesg_reweighing]
      ,[nom_zpu]
      ,[danger]
      ,[danger_kod]
      ,[cargo_returns]
      ,[id_station_on_amkr]
      ,[id_division_on_amkr]
      ,[empty_car]
      ,[kol_conductor]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[id_owner]
      ,[id_countrys]
      ,[id_genus]
      ,[kol_os]
      ,[usl_tip]
      ,[date_rem_uz]
      ,[date_rem_vag]
      ,[id_type_ownership]
      ,[gruzp_uz]
      ,[tara_uz]
      ,[zayava]
      ,[manual]
      ,[pay_summa]
      ,[id_wagons_rent_arrival]
  FROM [KRR-PA-CNT-Railway].[IDS].[Arrival_UZ_Vagon]
  where [id_cargo]=@id_cargo

  /****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[id_document]
      ,[num]
      ,[id_outgoing]
      ,[id_car]
      ,[id_condition]
      ,[id_wagons_rent_arrival]
      ,[id_wagons_rent_outgoing]
      ,[id_countrys]
      ,[id_genus]
      ,[id_owner]
      ,[gruzp_uz]
      ,[tara_uz]
      ,[note_uz]
      ,[gruzp]
      ,[u_tara]
      ,[ves_tary_arc]
      ,[id_warehouse]
      ,[id_division]
      ,[laden]
      ,[id_cargo]
      ,[id_cargo_gng]
      ,[vesg]
      ,[code_stn_to]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon]
  where [id_cargo]=@id_cargo