declare @num int = 52859873 
                     
       
SELECT TOP (1000) [num]
      ,[id_countrys]
      ,[id_genus]
      ,[id_owner]
      ,[id_operator]
      ,[change_operator]
      ,[gruzp]
      ,[tara]
      ,[kol_os]
      ,[usl_tip]
      ,[date_rem_uz]
      ,[date_rem_vag]
      ,[id_type_ownership]
      ,[sign]
      ,[factory_number]
      ,[inventory_number]
      ,[year_built]
      ,[exit_ban]
      ,[note]
      ,[sobstv_kis]
      ,[bit_warning]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[closed_route]
      ,[new_construction]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_Wagons]
  where num =@num

  declare @id_countrys int = (SELECT [id_countrys]FROM [KRR-PA-CNT-Railway].[IDS].[Directory_Wagons] where num =@num);
  declare @id_genus int = (SELECT [id_genus] FROM [KRR-PA-CNT-Railway].[IDS].[Directory_Wagons] where num =@num);

  select @id_countrys,@id_genus

UPDATE [IDS].[Arrival_UZ_Vagon]
   SET [id_countrys] = @id_countrys
      ,[id_genus] = @id_genus
WHERE num=@num 

UPDATE [IDS].[Outgoing_UZ_Vagon]
   SET [id_countrys] = @id_countrys
      ,[id_genus] = @id_genus
WHERE num=@num 



  SELECT [id]
      ,[abbr_ru]
      ,[genus_ru]
      ,[abbr_en]
      ,[genus_en]
      ,[rod_uz]
      ,[rod_default]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_GenusWagons]

SELECT TOP (1000) [id]
      ,[id_document]
      ,[num]
      ,[id_arrival]
      ,[id_car]
      --,[id_condition]
      --,[id_type]
      --,[gruzp]
      --,[u_tara]
      --,[ves_tary_arc]
      --,[route]
      --,[note_vagon]
      --,[id_cargo]
      --,[id_cargo_gng]
      --,[id_certification_data]
      --,[id_commercial_condition]
      --,[kol_pac]
      --,[pac]
      --,[vesg]
      --,[vesg_reweighing]
      --,[nom_zpu]
      --,[danger]
      --,[danger_kod]
      --,[cargo_returns]
      --,[id_station_on_amkr]
      --,[id_division_on_amkr]
      --,[empty_car]
      --,[kol_conductor]
      --,[create]
      --,[create_user]
      --,[change]
      --,[change_user]
      --,[id_owner]
      ,[id_countrys]
      ,[id_genus]
      --,[kol_os]
      --,[usl_tip]
      --,[date_rem_uz]
      --,[date_rem_vag]
      --,[id_type_ownership]
      --,[gruzp_uz]
      --,[tara_uz]
      --,[zayava]
      --,[manual]
      --,[pay_summa]
      --,[id_wagons_rent_arrival]
  FROM [KRR-PA-CNT-Railway].[IDS].[Arrival_UZ_Vagon]
  where num=@num 

SELECT TOP (1000) [id]
      ,[id_document]
      ,[num]
      ,[id_outgoing]
      ,[id_car]
      --,[id_condition]
      --,[id_wagons_rent_arrival]
      --,[id_wagons_rent_outgoing]
      ,[id_countrys]
      ,[id_genus]
      --,[id_owner]
      --,[gruzp_uz]
      --,[tara_uz]
      --,[note_uz]
      --,[gruzp]
      --,[u_tara]
      --,[ves_tary_arc]
      --,[id_warehouse]
      --,[id_division]
      --,[laden]
      --,[id_cargo]
      --,[id_cargo_gng]
      --,[vesg]
      --,[code_stn_to]
      --,[create]
      --,[create_user]
      --,[change]
      --,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon]
  where num=@num  