declare @num int = 56868052

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[num]
      ,[id_operator]
      ,[id_limiting]
      ,[rent_start]
      ,[rent_end]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[parent_id]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_WagonsRent]
  where num =@num
  order by 1 desc

SELECT TOP (1) [id]
      ,[num]
      ,[id_arrival_car]
      ,[id_sap_incoming_supply]
      ,[doc_outgoing_car]
      ,[id_outgoing_car]
      ,[id_sap_outbound_supply]
      ,[note]
      ,[create]
      ,[create_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
      ,[highlight_color]
      ,[id_usage_fee]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalRoutes]
  where num=@num
  order by 1 desc

  /****** Script for SelectTopNRows command from SSMS  ******/
SELECT [id]
      ,[id_arrival]
      ,[num]
      ,[position]
      ,[position_arrival]
      ,[consignee]
      ,[num_doc]
      ,[id_transfer]
      ,[note]
      ,[date_adoption_act]
      ,[arrival]
      ,[arrival_user]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[id_arrival_uz_vagon]
  FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars]
  where id=(Select top(1) [id_arrival_car] FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalRoutes] where num=@num order by 1 desc)

  /****** Script for SelectTopNRows command from SSMS  ******/
SELECT [id]
      --,[id_arrived]
      --,[id_sostav]
      --,[train]
      --,[composition_index]
      --,[date_arrival]
      ,[date_adoption]
      ,[date_adoption_act]
      --,[id_station_from]
      --,[id_station_on]
      --,[id_way]
      --,[numeration]
      --,[num_doc]
      --,[count]
      --,[status]
      --,[note]
      --,[create]
      --,[create_user]
      --,[change]
      --,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalSostav]
  where id =(SELECT TOP (1) [id_arrival] FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars] where id=(Select top(1) [id_arrival_car] FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalRoutes] where num=@num order by 1 desc))

  /****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      --,[id_document]
      --,[num]
      --,[id_arrival]
      --,[id_car]
      --,[id_condition]
      --,[id_type]
      --,[gruzp]
      --,[u_tara]
      --,[ves_tary_arc]
      --,[route]
      --,[note_vagon]
      --,[id_cargo]
      --,[id_cargo_gng]
      --,[id_certification_data]
      --,[id_commercial_condition]
      --,[kol_pac]
      --,[pac]
      --,[vesg]
      --,[vesg_reweighing]
      --,[nom_zpu]
      --,[danger]
      --,[danger_kod]
      --,[cargo_returns]
      --,[id_station_on_amkr]
      --,[id_division_on_amkr]
      --,[empty_car]
      --,[kol_conductor]
      --,[create]
      --,[create_user]
      --,[change]
      --,[change_user]
      --,[id_owner]
      --,[id_countrys]
      --,[id_genus]
      --,[kol_os]
      --,[usl_tip]
      --,[date_rem_uz]
      --,[date_rem_vag]
      --,[id_type_ownership]
      --,[gruzp_uz]
      --,[tara_uz]
      --,[zayava]
      --,[manual]
      --,[pay_summa]
      ,[id_wagons_rent_arrival]
  FROM [KRR-PA-CNT-Railway].[IDS].[Arrival_UZ_Vagon]
  where id = (SELECT TOP (1) [id_arrival_uz_vagon] FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars] where id=(Select top(1) [id_arrival_car] FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalRoutes] where num=@num order by 1 desc))