SELECT TOP (1000) [id]
      ,[station_name_ru]
      ,[station_name_en]
      ,[station_abbr_ru]
      ,[station_abbr_en]
      ,[exit_uz]
      ,[station_uz]
      ,[default_side]
      ,[code]
      ,[idle_time]
      ,[station_delete]
      ,[position]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_Station]

  SELECT TOP (1000) [id]
      ,[position]
      ,[name_division_ru]
      ,[name_division_en]
      ,[division_abbr_ru]
      ,[division_abbr_en]
      ,[id_type_devision]
      ,[code]
      ,[old]
      ,[parent_id]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_Divisions]
  order by [division_abbr_ru]

  SELECT TOP (1000) [id]
      ,[id_group]
      ,[cargo_name_ru]
      ,[cargo_name_en]
      ,[empty_weight]
      ,[code_sap]
      ,[material_class_sap]
      ,[id_cargo_ebd]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_InternalCargo]
  order by [cargo_name_ru]

  SELECT TOP (1000) [code]
      ,[station_name_ru]
      ,[station_name_en]
      ,[code_inlandrailway]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[port]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_ExternalStation]
  order by [station_name_ru]