declare @num_doc int = 78

SELECT [id]
      ,[id_arrived]
      ,[id_sostav]
      ,[train]
      ,[composition_index]
      ,[date_arrival]
      ,[date_adoption]
      ,[date_adoption_act]
      ,[id_station_from]
      ,[id_station_on]
      ,[id_way]
      ,[numeration]
      ,[num_doc]
      ,[count]
      ,[status]
      ,[note]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalSostav]
  where [num_doc] = @num_doc
  order by 1 desc

  SELECT TOP (1000) [id]
      ,[id_arrival]
      ,[num]
      ,[position]
      ,[position_arrival]
      ,[consignee]
      ,[num_doc]
      ,[id_transfer]
      ,[note]
      ,[date_adoption_act]
      ,[arrival]
      ,[arrival_user]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[id_arrival_uz_vagon]
  FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars]
  where [id_arrival] = (select top(1) [id] FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalSostav]  where [num_doc] = @num_doc order by 1 desc) and [position_arrival] is not null


  SELECT [id]
      ,[num]
      ,[id_arrival_car]
      ,[id_sap_incoming_supply]
      ,[doc_outgoing_car]
      ,[id_outgoing_car]
      ,[id_sap_outbound_supply]
      ,[note]
      ,[create]
      ,[create_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
      ,[highlight_color]
      ,[id_usage_fee]
      ,[note2]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalRoutes]
  where [id_arrival_car] in (select id FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars] where [id_arrival] = (select top(1) [id] FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalSostav]  where [num_doc] = @num_doc order by 1 desc) and [position_arrival] is not null)

  SELECT [id]
      ,[id_wagon_internal_routes]
      ,[id_operation]
      ,[operation_start]
      ,[operation_end]
      ,[id_condition]
      ,[id_loading_status]
      ,[locomotive1]
      ,[locomotive2]
      ,[note]
      ,[create]
      ,[create_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
      ,[con_change]
      ,[con_change_user]
      ,[id_organization_service]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalOperation]
  where [id_wagon_internal_routes] in (select id FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalRoutes] where [id_arrival_car] in (select id FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars] where [id_arrival] = (select top(1) [id] FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalSostav]  where [num_doc] = @num_doc order by 1 desc) and [position_arrival] is not null)
) and  [id_operation]=1

SELECT TOP (1000) [id]
      ,[id_wagon_internal_routes]
      ,[id_station]
      ,[id_way]
      ,[way_start]
      ,[way_end]
      ,[id_outer_way]
      ,[outer_way_start]
      ,[outer_way_end]
      ,[position]
      ,[note]
      ,[create]
      ,[create_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
      ,[id_wio]
      ,[num_sostav]
      ,[filing_start]
      ,[filing_end]
      ,[id_filing]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalMovement]
    where [id_wagon_internal_routes] in (select id FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalRoutes] where [id_arrival_car] in (select id FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars] where [id_arrival] = (select top(1) [id] FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalSostav]  where [num_doc] = @num_doc order by 1 desc) and [position_arrival] is not null)
)
	order by 1