declare @num int = 63267686


SELECT TOP (1000) [id]
      ,[id_wir]
      ,[num]
      ,[id_operator]
      ,[id_genus]
      ,[date_adoption]
      ,[date_outgoing]
      ,[route]
      ,[inp_cargo]
      ,[out_cargo]
      ,[derailment]
      ,[count_stage]
      ,[id_currency]
      ,[rate]
      ,[exchange_rate]
      ,[coefficient]
      ,[use_time]
      ,[grace_time]
      ,[calc_time]
      ,[calc_fee_amount]
      ,[manual_time]
      ,[manual_fee_amount]
      ,[note]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[downtime]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonUsageFee]
  where num=@num
  --
  SELECT [id]
      ,[num]
      ,[id_arrival_car]
      ,[id_sap_incoming_supply]
      ,[doc_outgoing_car]
      ,[id_outgoing_car]
      ,[id_sap_outbound_supply]
      ,[note]
      ,[create]
      ,[create_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
      ,[highlight_color]
      ,[id_usage_fee]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalRoutes]
  where id=(select top(1) [id_wir] FROM [KRR-PA-CNT-Railway].[IDS].[WagonUsageFee] where num=@num order by 1 desc)

  /****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[id_outgoing]
      ,[num]
      ,[position]
      ,[position_outgoing]
      ,[num_doc]
      ,[note]
      ,[date_outgoing_act]
      ,[outgoing]
      ,[outgoing_user]
      ,[id_outgoing_uz_vagon]
      ,[id_outgoing_detention]
      ,[id_reason_discrepancy_amkr]
      ,[id_reason_discrepancy_uz]
      ,[id_outgoing_return_start]
      ,[id_outgoing_return_stop]
      ,[parent_wir_id]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[note_vagonnik]
      ,[vagonnik]
      ,[vagonnik_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars]
  where id = (select top(1) [id_outgoing_car] FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalRoutes]
  where id=(select top(1) [id_wir] FROM [KRR-PA-CNT-Railway].[IDS].[WagonUsageFee] where num=@num order by 1 desc))

  /****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[num_doc]
      ,[id_station_from]
      ,[id_way_from]
      ,[id_station_on]
      ,[date_readiness_amkr]
      ,[date_end_inspection_acceptance_delivery]
      ,[date_end_inspection_loader]
      ,[date_end_inspection_vagonnik]
      ,[date_show_wagons]
      ,[date_readiness_uz]
      ,[date_outgoing]
      ,[date_outgoing_act]
      ,[date_departure_amkr]
      ,[composition_index]
      ,[status]
      ,[route_sign]
      ,[note]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[vagonnik_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingSostav]
  where id=231767