declare @num int = 60449063

SELECT TOP (1000) [id]
      ,[num]
      ,[id_arrival_car]
      ,[id_sap_incoming_supply]
      ,[doc_outgoing_car]
      ,[id_outgoing_car]
      ,[id_sap_outbound_supply]
      ,[note]
      ,[create]
      ,[create_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
      ,[highlight_color]
      ,[id_usage_fee]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalRoutes]
  where num = @num
  order by 1 desc

  SELECT TOP (1000) [id]
      ,[id_wir]
      ,[num]
      ,[id_operator]
      ,[id_genus]
      ,[date_adoption]
      ,[date_outgoing]
      ,[route]
      ,[inp_cargo]
      ,[out_cargo]
      ,[derailment]
      ,[count_stage]
      ,[id_currency]
      ,[rate]
      ,[exchange_rate]
      ,[coefficient]
      ,[use_time]
      ,[grace_time]
      ,[calc_time]
      ,[calc_fee_amount]
      ,[manual_time]
      ,[manual_fee_amount]
      ,[note]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[downtime]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonUsageFee]
  where num = @num
  order by 1 desc
