//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_UI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DirectoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DirectoryResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WEB_UI.App_LocalResources.DirectoryResource", typeof(DirectoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник &quot;Группы грузов ИДС&quot;.
        /// </summary>
        public static string cargo_group_title {
            get {
                return ResourceManager.GetString("cargo_group_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник &quot;Грузы ИДС&quot;.
        /// </summary>
        public static string cargo_title {
            get {
                return ResourceManager.GetString("cargo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник &quot;Вагонов ИДС&quot;.
        /// </summary>
        public static string cars_title {
            get {
                return ResourceManager.GetString("cars_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разметка коммерческого состояния вагона.
        /// </summary>
        public static string commercial_condition_description {
            get {
                return ResourceManager.GetString("commercial_condition_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коммерческое состояние.
        /// </summary>
        public static string commercial_condition_title {
            get {
                return ResourceManager.GetString("commercial_condition_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник &quot;Страны&quot;.
        /// </summary>
        public static string countrys_title {
            get {
                return ResourceManager.GetString("countrys_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник &quot;Внешние станции&quot;.
        /// </summary>
        public static string external_station_title {
            get {
                return ResourceManager.GetString("external_station_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочники.
        /// </summary>
        public static string home_title {
            get {
                return ResourceManager.GetString("home_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник «Внутренних железных дорог».
        /// </summary>
        public static string inland_railway_title {
            get {
                return ResourceManager.GetString("inland_railway_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструктивные письма по оформлению ЭПД на отправляемые вагоны..
        /// </summary>
        public static string instructional_letters_description {
            get {
                return ResourceManager.GetString("instructional_letters_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструктивные письма.
        /// </summary>
        public static string instructional_letters_title {
            get {
                return ResourceManager.GetString("instructional_letters_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник &quot;Операторы&quot;.
        /// </summary>
        public static string operators_wagons_title {
            get {
                return ResourceManager.GetString("operators_wagons_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Расставить текущее положение вагонов по путям станции.
        /// </summary>
        public static string park_state_description {
            get {
                return ResourceManager.GetString("park_state_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соcтояние парка.
        /// </summary>
        public static string park_state_title {
            get {
                return ResourceManager.GetString("park_state_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать предъявленный состав и произвести разметку вагонов.
        /// </summary>
        public static string present_wagon_marking_description {
            get {
                return ResourceManager.GetString("present_wagon_marking_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разметка по отправлению.
        /// </summary>
        public static string present_wagon_marking_title {
            get {
                return ResourceManager.GetString("present_wagon_marking_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник «Железных дорог».
        /// </summary>
        public static string railway_title {
            get {
                return ResourceManager.GetString("railway_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти вагон, показать историю перемещения..
        /// </summary>
        public static string search_wagon_description {
            get {
                return ResourceManager.GetString("search_wagon_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Найти вагон.
        /// </summary>
        public static string search_wagon_title {
            get {
                return ResourceManager.GetString("search_wagon_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник &quot;Грузоотправители&quot;.
        /// </summary>
        public static string shipper_title {
            get {
                return ResourceManager.GetString("shipper_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол. ос..
        /// </summary>
        public static string title_add_add_edit_kol_os {
            get {
                return ResourceManager.GetString("title_add_add_edit_kol_os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузы справочник ЕТ СНГ.
        /// </summary>
        public static string title_add_edit_cargo_etsng {
            get {
                return ResourceManager.GetString("title_add_edit_cargo_etsng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование груза в ИДС (анг.).
        /// </summary>
        public static string title_add_edit_cargo_name_en {
            get {
                return ResourceManager.GetString("title_add_edit_cargo_name_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование груза в ИДС (рус.).
        /// </summary>
        public static string title_add_edit_cargo_name_ru {
            get {
                return ResourceManager.GetString("title_add_edit_cargo_name_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изм. (УЗ).
        /// </summary>
        public static string title_add_edit_change_operator {
            get {
                return ResourceManager.GetString("title_add_edit_change_operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Замкнутый маршрут.
        /// </summary>
        public static string title_add_edit_closed_route {
            get {
                return ResourceManager.GetString("title_add_edit_closed_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код Europe.
        /// </summary>
        public static string title_add_edit_code_europe {
            get {
                return ResourceManager.GetString("title_add_edit_code_europe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код ISO.
        /// </summary>
        public static string title_add_edit_code_iso {
            get {
                return ResourceManager.GetString("title_add_edit_code_iso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код в SAP.
        /// </summary>
        public static string title_add_edit_code_sap {
            get {
                return ResourceManager.GetString("title_add_edit_code_sap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код СНГ.
        /// </summary>
        public static string title_add_edit_code_sng {
            get {
                return ResourceManager.GetString("title_add_edit_code_sng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое название страны (анг).
        /// </summary>
        public static string title_add_edit_country_abbr_en {
            get {
                return ResourceManager.GetString("title_add_edit_country_abbr_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое название страны (рус).
        /// </summary>
        public static string title_add_edit_country_abbr_ru {
            get {
                return ResourceManager.GetString("title_add_edit_country_abbr_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна дороги.
        /// </summary>
        public static string title_add_edit_countrys {
            get {
                return ResourceManager.GetString("title_add_edit_countrys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное название страны (анг).
        /// </summary>
        public static string title_add_edit_countrys_name_en {
            get {
                return ResourceManager.GetString("title_add_edit_countrys_name_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное название страны (рус).
        /// </summary>
        public static string title_add_edit_countrys_name_ru {
            get {
                return ResourceManager.GetString("title_add_edit_countrys_name_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рем. (УЗ).
        /// </summary>
        public static string title_add_edit_date_rem_uz {
            get {
                return ResourceManager.GetString("title_add_edit_date_rem_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рем. (Вагон).
        /// </summary>
        public static string title_add_edit_date_rem_vag {
            get {
                return ResourceManager.GetString("title_add_edit_date_rem_vag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрет выхода на УЗ (толька АМКР).
        /// </summary>
        public static string title_add_edit_exit_ban {
            get {
                return ResourceManager.GetString("title_add_edit_exit_ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заводской №.
        /// </summary>
        public static string title_add_edit_factory_number {
            get {
                return ResourceManager.GetString("title_add_edit_factory_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Груз-сть (УЗ).
        /// </summary>
        public static string title_add_edit_gruzp {
            get {
                return ResourceManager.GetString("title_add_edit_gruzp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорога.
        /// </summary>
        public static string title_add_edit_inlandrailway {
            get {
                return ResourceManager.GetString("title_add_edit_inlandrailway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое название дороги (анг).
        /// </summary>
        public static string title_add_edit_inlandrailway_abbr_en {
            get {
                return ResourceManager.GetString("title_add_edit_inlandrailway_abbr_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое название дороги (рус).
        /// </summary>
        public static string title_add_edit_inlandrailway_abbr_ru {
            get {
                return ResourceManager.GetString("title_add_edit_inlandrailway_abbr_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное название дороги (анг).
        /// </summary>
        public static string title_add_edit_inlandrailway_name_en {
            get {
                return ResourceManager.GetString("title_add_edit_inlandrailway_name_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное название дороги (рус).
        /// </summary>
        public static string title_add_edit_inlandrailway_name_ru {
            get {
                return ResourceManager.GetString("title_add_edit_inlandrailway_name_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инвентарный №.
        /// </summary>
        public static string title_add_edit_inventory_number {
            get {
                return ResourceManager.GetString("title_add_edit_inventory_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string title_add_edit_kod_adm {
            get {
                return ResourceManager.GetString("title_add_edit_kod_adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код дороги.
        /// </summary>
        public static string title_add_edit_kod_railway {
            get {
                return ResourceManager.GetString("title_add_edit_kod_railway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string title_add_edit_kod_rod {
            get {
                return ResourceManager.GetString("title_add_edit_kod_rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код станции.
        /// </summary>
        public static string title_add_edit_kod_station {
            get {
                return ResourceManager.GetString("title_add_edit_kod_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограничение (АМКР).
        /// </summary>
        public static string title_add_edit_limiting {
            get {
                return ResourceManager.GetString("title_add_edit_limiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При изменении оператора (АМКР) будет создана новая строка, с новым оператором и определена дата начало аренды. По старой строке окончание аренды будет выставлено автоматически по дате начала новой аренды..
        /// </summary>
        public static string title_add_edit_message_new_operator {
            get {
                return ResourceManager.GetString("title_add_edit_message_new_operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Админ..
        /// </summary>
        public static string title_add_edit_name_adm {
            get {
                return ResourceManager.GetString("title_add_edit_name_adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Род вагона.
        /// </summary>
        public static string title_add_edit_name_rod {
            get {
                return ResourceManager.GetString("title_add_edit_name_rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Род (абр.).
        /// </summary>
        public static string title_add_edit_name_rod_abbr {
            get {
                return ResourceManager.GetString("title_add_edit_name_rod_abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нова побудова.
        /// </summary>
        public static string title_add_edit_new_construction {
            get {
                return ResourceManager.GetString("title_add_edit_new_construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограничения (УЗ).
        /// </summary>
        public static string title_add_edit_note {
            get {
                return ResourceManager.GetString("title_add_edit_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер вагона.
        /// </summary>
        public static string title_add_edit_num {
            get {
                return ResourceManager.GetString("title_add_edit_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор (АМКР).
        /// </summary>
        public static string title_add_edit_operator_car {
            get {
                return ResourceManager.GetString("title_add_edit_operator_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый оператор (АМКР).
        /// </summary>
        public static string title_add_edit_operator_car_new {
            get {
                return ResourceManager.GetString("title_add_edit_operator_car_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало аренды.
        /// </summary>
        public static string title_add_edit_operator_car_rent_start {
            get {
                return ResourceManager.GetString("title_add_edit_operator_car_rent_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор (УЗ).
        /// </summary>
        public static string title_add_edit_operator_uz_car {
            get {
                return ResourceManager.GetString("title_add_edit_operator_uz_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Собственник (УЗ).
        /// </summary>
        public static string title_add_edit_owner_car {
            get {
                return ResourceManager.GetString("title_add_edit_owner_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорога страны.
        /// </summary>
        public static string title_add_edit_railway {
            get {
                return ResourceManager.GetString("title_add_edit_railway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое название дороги (анг).
        /// </summary>
        public static string title_add_edit_railway_abbr_en {
            get {
                return ResourceManager.GetString("title_add_edit_railway_abbr_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Краткое название дороги (рус).
        /// </summary>
        public static string title_add_edit_railway_abbr_ru {
            get {
                return ResourceManager.GetString("title_add_edit_railway_abbr_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное название дороги (анг).
        /// </summary>
        public static string title_add_edit_railway_name_en {
            get {
                return ResourceManager.GetString("title_add_edit_railway_name_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Полное название дороги (рус).
        /// </summary>
        public static string title_add_edit_railway_name_ru {
            get {
                return ResourceManager.GetString("title_add_edit_railway_name_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправляемые грузы.
        /// </summary>
        public static string title_add_edit_sending {
            get {
                return ResourceManager.GetString("title_add_edit_sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Призн. сход\не груз..
        /// </summary>
        public static string title_add_edit_sign {
            get {
                return ResourceManager.GetString("title_add_edit_sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название станции (анг).
        /// </summary>
        public static string title_add_edit_station_name_en {
            get {
                return ResourceManager.GetString("title_add_edit_station_name_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название станции (рус).
        /// </summary>
        public static string title_add_edit_station_name_ru {
            get {
                return ResourceManager.GetString("title_add_edit_station_name_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тара (УЗ).
        /// </summary>
        public static string title_add_edit_tara {
            get {
                return ResourceManager.GetString("title_add_edit_tara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Призн. собст..
        /// </summary>
        public static string title_add_edit_type_ownership {
            get {
                return ResourceManager.GetString("title_add_edit_type_ownership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип цист..
        /// </summary>
        public static string title_add_edit_usl_tip {
            get {
                return ResourceManager.GetString("title_add_edit_usl_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контроль системной нумерации.
        /// </summary>
        public static string title_add_edit_valodation_num {
            get {
                return ResourceManager.GetString("title_add_edit_valodation_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Год постр..
        /// </summary>
        public static string title_add_edit_year_built {
            get {
                return ResourceManager.GetString("title_add_edit_year_built", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группы грузов в ИДС.
        /// </summary>
        public static string title_change_group_cargo_group {
            get {
                return ResourceManager.GetString("title_change_group_cargo_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый номер.
        /// </summary>
        public static string title_change_num_new {
            get {
                return ResourceManager.GetString("title_change_num_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старый номер.
        /// </summary>
        public static string title_change_num_old {
            get {
                return ResourceManager.GetString("title_change_num_old", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время осмотра вагонником.
        /// </summary>
        public static string title_close_condition_date {
            get {
                return ResourceManager.GetString("title_close_condition_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать.
        /// </summary>
        public static string title_create {
            get {
                return ResourceManager.GetString("title_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string title_delete {
            get {
                return ResourceManager.GetString("title_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разметка после осмотра.
        /// </summary>
        public static string title_edit_note_vagonnik {
            get {
                return ResourceManager.GetString("title_edit_note_vagonnik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статусы.
        /// </summary>
        public static string title_park_status {
            get {
                return ResourceManager.GetString("title_park_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По сотоянию на.
        /// </summary>
        public static string title_park_status_on_dt {
            get {
                return ResourceManager.GetString("title_park_status_on_dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция.
        /// </summary>
        public static string title_station {
            get {
                return ResourceManager.GetString("title_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать прибывший состав и произвести разметку вагонов.
        /// </summary>
        public static string wagon_marking_description {
            get {
                return ResourceManager.GetString("wagon_marking_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разметка по прибытию.
        /// </summary>
        public static string wagon_marking_title {
            get {
                return ResourceManager.GetString("wagon_marking_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник &quot;Путей&quot;.
        /// </summary>
        public static string ways_title {
            get {
                return ResourceManager.GetString("ways_title", resourceCulture);
            }
        }
    }
}
