//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_UI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DirectoryResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DirectoryResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WEB_UI.App_LocalResources.DirectoryResource", typeof(DirectoryResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник &quot;Группы грузов ИДС&quot;.
        /// </summary>
        public static string cargo_group_title {
            get {
                return ResourceManager.GetString("cargo_group_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник &quot;Грузы ИДС&quot;.
        /// </summary>
        public static string cargo_title {
            get {
                return ResourceManager.GetString("cargo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник &quot;Вагонов ИДС&quot;.
        /// </summary>
        public static string cars_title {
            get {
                return ResourceManager.GetString("cars_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочники.
        /// </summary>
        public static string home_title {
            get {
                return ResourceManager.GetString("home_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол. ос..
        /// </summary>
        public static string title_add_add_edit_kol_os {
            get {
                return ResourceManager.GetString("title_add_add_edit_kol_os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузы справочник ЕТ СНГ.
        /// </summary>
        public static string title_add_edit_cargo_etsng {
            get {
                return ResourceManager.GetString("title_add_edit_cargo_etsng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование груза в ИДС (анг.).
        /// </summary>
        public static string title_add_edit_cargo_name_en {
            get {
                return ResourceManager.GetString("title_add_edit_cargo_name_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование груза в ИДС (рус.).
        /// </summary>
        public static string title_add_edit_cargo_name_ru {
            get {
                return ResourceManager.GetString("title_add_edit_cargo_name_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код в SAP.
        /// </summary>
        public static string title_add_edit_code_sap {
            get {
                return ResourceManager.GetString("title_add_edit_code_sap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рем. (УЗ).
        /// </summary>
        public static string title_add_edit_date_rem_uz {
            get {
                return ResourceManager.GetString("title_add_edit_date_rem_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата рем. вагон.
        /// </summary>
        public static string title_add_edit_date_rem_vag {
            get {
                return ResourceManager.GetString("title_add_edit_date_rem_vag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Груз-сть (УЗ).
        /// </summary>
        public static string title_add_edit_gruzp {
            get {
                return ResourceManager.GetString("title_add_edit_gruzp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string title_add_edit_kod_adm {
            get {
                return ResourceManager.GetString("title_add_edit_kod_adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string title_add_edit_kod_rod {
            get {
                return ResourceManager.GetString("title_add_edit_kod_rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограничение (АМКР).
        /// </summary>
        public static string title_add_edit_limiting {
            get {
                return ResourceManager.GetString("title_add_edit_limiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на При изменении оператора (АМКР) будет создана новая строка, с новым оператором и определена дата начало аренды. По старой строке окончание аренды будет выставлено автоматически по дате начала новой аренды..
        /// </summary>
        public static string title_add_edit_message_new_operator {
            get {
                return ResourceManager.GetString("title_add_edit_message_new_operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Админ..
        /// </summary>
        public static string title_add_edit_name_adm {
            get {
                return ResourceManager.GetString("title_add_edit_name_adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Род вагона.
        /// </summary>
        public static string title_add_edit_name_rod {
            get {
                return ResourceManager.GetString("title_add_edit_name_rod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Род (абр.).
        /// </summary>
        public static string title_add_edit_name_rod_abbr {
            get {
                return ResourceManager.GetString("title_add_edit_name_rod_abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание.
        /// </summary>
        public static string title_add_edit_note {
            get {
                return ResourceManager.GetString("title_add_edit_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер вагона.
        /// </summary>
        public static string title_add_edit_num {
            get {
                return ResourceManager.GetString("title_add_edit_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор (АМКР).
        /// </summary>
        public static string title_add_edit_operator_car {
            get {
                return ResourceManager.GetString("title_add_edit_operator_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый оператор (АМКР).
        /// </summary>
        public static string title_add_edit_operator_car_new {
            get {
                return ResourceManager.GetString("title_add_edit_operator_car_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало аренды.
        /// </summary>
        public static string title_add_edit_operator_car_rent_start {
            get {
                return ResourceManager.GetString("title_add_edit_operator_car_rent_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор (УЗ).
        /// </summary>
        public static string title_add_edit_operator_uz_car {
            get {
                return ResourceManager.GetString("title_add_edit_operator_uz_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Собственник.
        /// </summary>
        public static string title_add_edit_owner_car {
            get {
                return ResourceManager.GetString("title_add_edit_owner_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправляемые грузы.
        /// </summary>
        public static string title_add_edit_sending {
            get {
                return ResourceManager.GetString("title_add_edit_sending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Призн. сход\не груз..
        /// </summary>
        public static string title_add_edit_sign {
            get {
                return ResourceManager.GetString("title_add_edit_sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Призн. собст..
        /// </summary>
        public static string title_add_edit_type_ownership {
            get {
                return ResourceManager.GetString("title_add_edit_type_ownership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип цист..
        /// </summary>
        public static string title_add_edit_usl_tip {
            get {
                return ResourceManager.GetString("title_add_edit_usl_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группы грузов в ИДС.
        /// </summary>
        public static string title_change_group_cargo_group {
            get {
                return ResourceManager.GetString("title_change_group_cargo_group", resourceCulture);
            }
        }
    }
}
