//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_UI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GlobalResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WEB_UI.App_LocalResources.GlobalResource", typeof(GlobalResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Eduard.Levchenko@arcelormittal.com.
        /// </summary>
        public static string contact_admin_email {
            get {
                return ResourceManager.GetString("contact_admin_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 96332.
        /// </summary>
        public static string contact_admin_phone {
            get {
                return ResourceManager.GetString("contact_admin_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техническая поддержка, администрирование сайта : Левченко Эдуард.
        /// </summary>
        public static string contact_admin_title {
            get {
                return ResourceManager.GetString("contact_admin_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Irina.Shuba@arcelormittal.com.
        /// </summary>
        public static string contact_rail_transport_email {
            get {
                return ResourceManager.GetString("contact_rail_transport_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 91932.
        /// </summary>
        public static string contact_rail_transport_phone {
            get {
                return ResourceManager.GetString("contact_rail_transport_phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техническая поддержка, ВДС «ЖД АМКР»: Шуба Ирина.
        /// </summary>
        public static string contact_rail_transport_title {
            get {
                return ResourceManager.GetString("contact_rail_transport_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для учетной  записи:.
        /// </summary>
        public static string error_ad_text1 {
            get {
                return ResourceManager.GetString("error_ad_text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на доступ запрещен к ресурсу.
        /// </summary>
        public static string error_ad_text2 {
            get {
                return ResourceManager.GetString("error_ad_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка! Извините что-то пошло не так..
        /// </summary>
        public static string error_message {
            get {
                return ResourceManager.GetString("error_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контакты.
        /// </summary>
        public static string home_link_contact {
            get {
                return ResourceManager.GetString("home_link_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструкции.
        /// </summary>
        public static string home_link_document {
            get {
                return ResourceManager.GetString("home_link_document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string home_link_home {
            get {
                return ResourceManager.GetString("home_link_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сервисы.
        /// </summary>
        public static string home_link_services {
            get {
                return ResourceManager.GetString("home_link_services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Системы.
        /// </summary>
        public static string home_link_system {
            get {
                return ResourceManager.GetString("home_link_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        public static string home_menu {
            get {
                return ResourceManager.GetString("home_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информационно диспетчерская система.
        /// </summary>
        public static string home_title {
            get {
                return ResourceManager.GetString("home_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информационно диспетчерская система.
        /// </summary>
        public static string home_title1 {
            get {
                return ResourceManager.GetString("home_title1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Транспортный департамент ArcelorMittal Кривой Рог.
        /// </summary>
        public static string home_title2 {
            get {
                return ResourceManager.GetString("home_title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ru-RU.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти.
        /// </summary>
        public static string link_goto {
            get {
                return ResourceManager.GetString("link_goto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информационно-диспетчерская система «Управление собственным подвижным составом АРСЕЛОРМИТТАЛ КРИВОЙ РОГ».
        /// </summary>
        public static string system_idsmors_description {
            get {
                return ResourceManager.GetString("system_idsmors_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИДС &quot;УСПС&quot;.
        /// </summary>
        public static string system_idsmors_title {
            get {
                return ResourceManager.GetString("system_idsmors_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «Железнодорожный транспорт АМКР» - внутренняя диспетчерская система оперативного управления перевозочным процессом на железнодорожном транспорте  внутри предприятияПАО «АРСЕЛОРМИТТАЛ КРИВОЙ РОГ».
        /// </summary>
        public static string system_rail_transport_description {
            get {
                return ResourceManager.GetString("system_rail_transport_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВДС «ЖД АМКР».
        /// </summary>
        public static string system_rail_transport_title {
            get {
                return ResourceManager.GetString("system_rail_transport_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аналитическая отчетность транспортного департамента ПАО «АРСЕЛОРМИТТАЛ КРИВОЙ РОГ».
        /// </summary>
        public static string system_transport_department_description {
            get {
                return ResourceManager.GetString("system_transport_department_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ТД.
        /// </summary>
        public static string system_transport_department_title {
            get {
                return ResourceManager.GetString("system_transport_department_title", resourceCulture);
            }
        }
    }
}
