//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_UI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IDSMORSResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IDSMORSResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WEB_UI.App_LocalResources.IDSMORSResource", typeof(IDSMORSResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string bt_delete_text {
            get {
                return ResourceManager.GetString("bt_delete_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Править.
        /// </summary>
        public static string bt_edit_text {
            get {
                return ResourceManager.GetString("bt_edit_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Электронные карточки с техническими характеристиками подвижного состава..
        /// </summary>
        public static string ecards_description {
            get {
                return ResourceManager.GetString("ecards_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КАРТОЧКИ.
        /// </summary>
        public static string ecards_title {
            get {
                return ResourceManager.GetString("ecards_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Род подвижного сотава.
        /// </summary>
        public static string genus_wagon_label {
            get {
                return ResourceManager.GetString("genus_wagon_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Основные характеристики.
        /// </summary>
        public static string legend_main_characteristics {
            get {
                return ResourceManager.GetString("legend_main_characteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер вагона.
        /// </summary>
        public static string num_wagon_label {
            get {
                return ResourceManager.GetString("num_wagon_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Парк подвижного состава, сгруппированный по параметрам..
        /// </summary>
        public static string park_description {
            get {
                return ResourceManager.GetString("park_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПАРК.
        /// </summary>
        public static string park_title {
            get {
                return ResourceManager.GetString("park_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Государство собственник.
        /// </summary>
        public static string state_label {
            get {
                return ResourceManager.GetString("state_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция приписки.
        /// </summary>
        public static string station_label {
            get {
                return ResourceManager.GetString("station_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информационно-диспетчерская система «Управление собственным подвижным составом АРСЕЛОРМИТТАЛ КРИВОЙ РОГ».
        /// </summary>
        public static string system_idsmors_description {
            get {
                return ResourceManager.GetString("system_idsmors_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИДС &quot; УСПС&quot;.
        /// </summary>
        public static string system_idsmors_title {
            get {
                return ResourceManager.GetString("system_idsmors_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип подвижного сотава.
        /// </summary>
        public static string type_wagon_label {
            get {
                return ResourceManager.GetString("type_wagon_label", resourceCulture);
            }
        }
    }
}
