//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_UI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IDSRWTResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IDSRWTResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WEB_UI.App_LocalResources.IDSRWTResource", typeof(IDSRWTResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны АМКР на подходах и станциях УЗ Кривого Рога.
        /// </summary>
        public static string arrival_description {
            get {
                return ResourceManager.GetString("arrival_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подходы.
        /// </summary>
        public static string arrival_title {
            get {
                return ResourceManager.GetString("arrival_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номерной учет по прибытию, прием груза.
        /// </summary>
        public static string incoming_description {
            get {
                return ResourceManager.GetString("incoming_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принять на АМКР.
        /// </summary>
        public static string incoming_title {
            get {
                return ResourceManager.GetString("incoming_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номерной учет вагонов, отправляемых из АМКР на внешнюю сеть (УЗ).
        /// </summary>
        public static string outgoing_description {
            get {
                return ResourceManager.GetString("outgoing_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить на УЗ.
        /// </summary>
        public static string outgoing_title {
            get {
                return ResourceManager.GetString("outgoing_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «Железнодорожный транспорт АМКР» - внутренняя диспетчерская система оперативного управления перевозочным процессом на железнодорожном транспорте  внутри предприятияПАО «АРСЕЛОРМИТТАЛ КРИВОЙ РОГ».
        /// </summary>
        public static string system_idsrwt_description {
            get {
                return ResourceManager.GetString("system_idsrwt_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВДС «ЖД АМКР».
        /// </summary>
        public static string system_idsrwt_title {
            get {
                return ResourceManager.GetString("system_idsrwt_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адм.(код).
        /// </summary>
        public static string title_adm_kod {
            get {
                return ResourceManager.GetString("title_adm_kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Администрация.
        /// </summary>
        public static string title_adm_name {
            get {
                return ResourceManager.GetString("title_adm_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество вагонов.
        /// </summary>
        public static string title_arrival_count_car {
            get {
                return ResourceManager.GetString("title_arrival_count_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принять на станцию.
        /// </summary>
        public static string title_arrival_station_on {
            get {
                return ResourceManager.GetString("title_arrival_station_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принять на путь.
        /// </summary>
        public static string title_arrival_way_on {
            get {
                return ResourceManager.GetString("title_arrival_way_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата и время перехода.
        /// </summary>
        public static string title_border_cross_time {
            get {
                return ResourceManager.GetString("title_border_cross_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пограничный пункт.
        /// </summary>
        public static string title_border_point {
            get {
                return ResourceManager.GetString("title_border_point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бригадир погрузки.
        /// </summary>
        public static string title_brigadier_loading {
            get {
                return ResourceManager.GetString("title_brigadier_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время и дата приема по акту.
        /// </summary>
        public static string title_car_date_adoption_act {
            get {
                return ResourceManager.GetString("title_car_date_adoption_act", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата сдачи по акту.
        /// </summary>
        public static string title_car_date_outgoing_act {
            get {
                return ResourceManager.GetString("title_car_date_outgoing_act", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточка вагона.
        /// </summary>
        public static string title_card_vag {
            get {
                return ResourceManager.GetString("title_card_vag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Груз.
        /// </summary>
        public static string title_cargo {
            get {
                return ResourceManager.GetString("title_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Анализ груза.
        /// </summary>
        public static string title_cargo_analysis {
            get {
                return ResourceManager.GetString("title_cargo_analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наименование груза.
        /// </summary>
        public static string title_cargo_name {
            get {
                return ResourceManager.GetString("title_cargo_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Признак возврата поставщику.
        /// </summary>
        public static string title_cargo_returns {
            get {
                return ResourceManager.GetString("title_cargo_returns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сертификатные данные.
        /// </summary>
        public static string title_certificate_data {
            get {
                return ResourceManager.GetString("title_certificate_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string title_client_kod {
            get {
                return ResourceManager.GetString("title_client_kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузоотправитель.
        /// </summary>
        public static string title_client_name_from {
            get {
                return ResourceManager.GetString("title_client_name_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузополучатель.
        /// </summary>
        public static string title_client_name_on {
            get {
                return ResourceManager.GetString("title_client_name_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коммерческое состояние.
        /// </summary>
        public static string title_commercial_condition {
            get {
                return ResourceManager.GetString("title_commercial_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индекс поезда.
        /// </summary>
        public static string title_composition_index {
            get {
                return ResourceManager.GetString("title_composition_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите индекс поезда.
        /// </summary>
        public static string title_composition_index_invalid {
            get {
                return ResourceManager.GetString("title_composition_index_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разметка (прибытие).
        /// </summary>
        public static string title_condition_arrival {
            get {
                return ResourceManager.GetString("title_condition_arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разметка (выгрузка).
        /// </summary>
        public static string title_condition_provide {
            get {
                return ResourceManager.GetString("title_condition_provide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контейнера.
        /// </summary>
        public static string title_container {
            get {
                return ResourceManager.GetString("title_container", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Класс.
        /// </summary>
        public static string title_danger_class {
            get {
                return ResourceManager.GetString("title_danger_class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код опасности.
        /// </summary>
        public static string title_danger_kod {
            get {
                return ResourceManager.GetString("title_danger_kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание класса опасности.
        /// </summary>
        public static string title_danger_name {
            get {
                return ResourceManager.GetString("title_danger_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные о прибытии.
        /// </summary>
        public static string title_data_arrival {
            get {
                return ResourceManager.GetString("title_data_arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время приема.
        /// </summary>
        public static string title_date_adoption {
            get {
                return ResourceManager.GetString("title_date_adoption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время приема по акту.
        /// </summary>
        public static string title_date_adoption_act {
            get {
                return ResourceManager.GetString("title_date_adoption_act", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата и время прибытия.
        /// </summary>
        public static string title_date_arrival {
            get {
                return ResourceManager.GetString("title_date_arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите дату и время прибытия.
        /// </summary>
        public static string title_date_arrival_invalid {
            get {
                return ResourceManager.GetString("title_date_arrival_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата ремонта (БД УЗ).
        /// </summary>
        public static string title_date_rem_uz {
            get {
                return ResourceManager.GetString("title_date_rem_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата ремонта (вагон).
        /// </summary>
        public static string title_date_rem_vag {
            get {
                return ResourceManager.GetString("title_date_rem_vag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задержание.
        /// </summary>
        public static string title_detention {
            get {
                return ResourceManager.GetString("title_detention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задержание.
        /// </summary>
        public static string title_detention_bit {
            get {
                return ResourceManager.GetString("title_detention_bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Задержание/Возврат.
        /// </summary>
        public static string title_detention_return {
            get {
                return ResourceManager.GetString("title_detention_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цех получатель.
        /// </summary>
        public static string title_devision_on_amkr {
            get {
                return ResourceManager.GetString("title_devision_on_amkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шифр.
        /// </summary>
        public static string title_devision_on_amkr_kod {
            get {
                return ResourceManager.GetString("title_devision_on_amkr_kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цех\склад.
        /// </summary>
        public static string title_devision_on_amkr_name {
            get {
                return ResourceManager.GetString("title_devision_on_amkr_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тарифное расстояние.
        /// </summary>
        public static string title_distance_way {
            get {
                return ResourceManager.GetString("title_distance_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата обновления.
        /// </summary>
        public static string title_doc_dt {
            get {
                return ResourceManager.GetString("title_doc_dt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Статус.
        /// </summary>
        public static string title_doc_status {
            get {
                return ResourceManager.GetString("title_doc_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создана.
        /// </summary>
        public static string title_dt_input_sipply {
            get {
                return ResourceManager.GetString("title_dt_input_sipply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ЭПД (после принятия УЗ).
        /// </summary>
        public static string title_epd {
            get {
                return ResourceManager.GetString("title_epd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Группа груза.
        /// </summary>
        public static string title_group_cargo {
            get {
                return ResourceManager.GetString("title_group_cargo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузоп. (ЭПД),т.
        /// </summary>
        public static string title_gruzp_doc {
            get {
                return ResourceManager.GetString("title_gruzp_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузоп. (УЗ),т.
        /// </summary>
        public static string title_gruzp_uz {
            get {
                return ResourceManager.GetString("title_gruzp_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код Адм..
        /// </summary>
        public static string title_kod_adm {
            get {
                return ResourceManager.GetString("title_kod_adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код ЕТСНГ.
        /// </summary>
        public static string title_kod_etsng {
            get {
                return ResourceManager.GetString("title_kod_etsng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код ГНГ.
        /// </summary>
        public static string title_kod_gng {
            get {
                return ResourceManager.GetString("title_kod_gng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string title_kod_plat {
            get {
                return ResourceManager.GetString("title_kod_plat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество осей.
        /// </summary>
        public static string title_kol_os {
            get {
                return ResourceManager.GetString("title_kol_os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол. мест.
        /// </summary>
        public static string title_kol_pac {
            get {
                return ResourceManager.GetString("title_kol_pac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограничение погрузки.
        /// </summary>
        public static string title_limiting_loading {
            get {
                return ResourceManager.GetString("title_limiting_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограничение (АМКР).
        /// </summary>
        public static string title_limiting_loading_amkr {
            get {
                return ResourceManager.GetString("title_limiting_loading_amkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограничение (УЗ).
        /// </summary>
        public static string title_limiting_loading_uz {
            get {
                return ResourceManager.GetString("title_limiting_loading_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инструктивные письма.
        /// </summary>
        public static string title_link_letters {
            get {
                return ResourceManager.GetString("title_link_letters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние парка.
        /// </summary>
        public static string title_link_park_state {
            get {
                return ResourceManager.GetString("title_link_park_state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск вагона.
        /// </summary>
        public static string title_link_searsh_wagon {
            get {
                return ResourceManager.GetString("title_link_searsh_wagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карточка вагонов.
        /// </summary>
        public static string title_link_wagon_dir {
            get {
                return ResourceManager.GetString("title_link_wagon_dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разметка вагонов.
        /// </summary>
        public static string title_link_wagon_marking {
            get {
                return ResourceManager.GetString("title_link_wagon_marking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Груж/порожний.
        /// </summary>
        public static string title_loaded_car {
            get {
                return ResourceManager.GetString("title_loaded_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные о погрузке.
        /// </summary>
        public static string title_loading_data {
            get {
                return ResourceManager.GetString("title_loading_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цех погрузки.
        /// </summary>
        public static string title_loading_devision {
            get {
                return ResourceManager.GetString("title_loading_devision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шифр.
        /// </summary>
        public static string title_loading_devision_code {
            get {
                return ResourceManager.GetString("title_loading_devision_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Материал.
        /// </summary>
        public static string title_material {
            get {
                return ResourceManager.GetString("title_material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код материала.
        /// </summary>
        public static string title_material_code {
            get {
                return ResourceManager.GetString("title_material_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название материала.
        /// </summary>
        public static string title_material_name {
            get {
                return ResourceManager.GetString("title_material_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна.
        /// </summary>
        public static string title_name_adm {
            get {
                return ResourceManager.GetString("title_name_adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название груза по ЕТСНГ.
        /// </summary>
        public static string title_name_etsng {
            get {
                return ResourceManager.GetString("title_name_etsng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название груза по ГНГ.
        /// </summary>
        public static string title_name_gng {
            get {
                return ResourceManager.GetString("title_name_gng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор.
        /// </summary>
        public static string title_name_operator {
            get {
                return ResourceManager.GetString("title_name_operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Собственник.
        /// </summary>
        public static string title_name_owner {
            get {
                return ResourceManager.GetString("title_name_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Плательщик с ЭПД.
        /// </summary>
        public static string title_name_plat {
            get {
                return ResourceManager.GetString("title_name_plat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Род вагона.
        /// </summary>
        public static string title_name_rod_vag {
            get {
                return ResourceManager.GetString("title_name_rod_vag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № ЗПУ.
        /// </summary>
        public static string title_nom_zpu {
            get {
                return ResourceManager.GetString("title_nom_zpu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Признак не грузить.
        /// </summary>
        public static string title_not_load {
            get {
                return ResourceManager.GetString("title_not_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание.
        /// </summary>
        public static string title_note {
            get {
                return ResourceManager.GetString("title_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на  Ограничения УЗ (БД УЗ).
        /// </summary>
        public static string title_note_uz {
            get {
                return ResourceManager.GetString("title_note_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Вагона.
        /// </summary>
        public static string title_num_car {
            get {
                return ResourceManager.GetString("title_num_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № контейнера.
        /// </summary>
        public static string title_num_cont {
            get {
                return ResourceManager.GetString("title_num_cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № ЭПД.
        /// </summary>
        public static string title_num_doc {
            get {
                return ResourceManager.GetString("title_num_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Входящей поставки.
        /// </summary>
        public static string title_num_input_sipply {
            get {
                return ResourceManager.GetString("title_num_input_sipply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Ревизии.
        /// </summary>
        public static string title_num_rev {
            get {
                return ResourceManager.GetString("title_num_rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Ведомости.
        /// </summary>
        public static string title_num_sheet {
            get {
                return ResourceManager.GetString("title_num_sheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало нумерации.
        /// </summary>
        public static string title_numeration {
            get {
                return ResourceManager.GetString("title_numeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ПРИНЯТЬ.
        /// </summary>
        public static string title_operation_arrival_run {
            get {
                return ResourceManager.GetString("title_operation_arrival_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибывает с внешнего пути.
        /// </summary>
        public static string title_operation_detali_arrival_outer_ways {
            get {
                return ResourceManager.GetString("title_operation_detali_arrival_outer_ways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибывает на станцию.
        /// </summary>
        public static string title_operation_detali_arrival_station {
            get {
                return ResourceManager.GetString("title_operation_detali_arrival_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь приема состава.
        /// </summary>
        public static string title_operation_detali_arrival_way {
            get {
                return ResourceManager.GetString("title_operation_detali_arrival_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время выполнения.
        /// </summary>
        public static string title_operation_detali_lead_time {
            get {
                return ResourceManager.GetString("title_operation_detali_lead_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Локомотив.
        /// </summary>
        public static string title_operation_detali_locomotive {
            get {
                return ResourceManager.GetString("title_operation_detali_locomotive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция отправки.
        /// </summary>
        public static string title_operation_detali_provide_station {
            get {
                return ResourceManager.GetString("title_operation_detali_provide_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь с составом для предъявления.
        /// </summary>
        public static string title_operation_detali_provide_way_from {
            get {
                return ResourceManager.GetString("title_operation_detali_provide_way_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить реверс.
        /// </summary>
        public static string title_operation_detali_reverse {
            get {
                return ResourceManager.GetString("title_operation_detali_reverse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер поезда.
        /// </summary>
        public static string title_operation_detali_sending_num_train {
            get {
                return ResourceManager.GetString("title_operation_detali_sending_num_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перегон.
        /// </summary>
        public static string title_operation_detali_sending_outer_ways {
            get {
                return ResourceManager.GetString("title_operation_detali_sending_outer_ways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить на станцию.
        /// </summary>
        public static string title_operation_detali_sending_station {
            get {
                return ResourceManager.GetString("title_operation_detali_sending_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сторона.
        /// </summary>
        public static string title_operation_detali_side {
            get {
                return ResourceManager.GetString("title_operation_detali_side", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция.
        /// </summary>
        public static string title_operation_detali_station {
            get {
                return ResourceManager.GetString("title_operation_detali_station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь.
        /// </summary>
        public static string title_operation_detali_way {
            get {
                return ResourceManager.GetString("title_operation_detali_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь отправки.
        /// </summary>
        public static string title_operation_detali_way_from {
            get {
                return ResourceManager.GetString("title_operation_detali_way_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь приема.
        /// </summary>
        public static string title_operation_detali_way_on {
            get {
                return ResourceManager.GetString("title_operation_detali_way_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВЫПОЛНИТЬ.
        /// </summary>
        public static string title_operation_run {
            get {
                return ResourceManager.GetString("title_operation_run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция начата.
        /// </summary>
        public static string title_operation_start {
            get {
                return ResourceManager.GetString("title_operation_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Операция закончена.
        /// </summary>
        public static string title_operation_stop {
            get {
                return ResourceManager.GetString("title_operation_stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оплата.
        /// </summary>
        public static string title_payer {
            get {
                return ResourceManager.GetString("title_payer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № позиции.
        /// </summary>
        public static string title_pos_input_sipply {
            get {
                return ResourceManager.GetString("title_pos_input_sipply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № в поезде.
        /// </summary>
        public static string title_position {
            get {
                return ResourceManager.GetString("title_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорога.
        /// </summary>
        public static string title_railway_name {
            get {
                return ResourceManager.GetString("title_railway_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причина расх. сдачи по времени АМКР.
        /// </summary>
        public static string title_reason_discrepancy_amkr {
            get {
                return ResourceManager.GetString("title_reason_discrepancy_amkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причина расх. сдачи по времени УЗ.
        /// </summary>
        public static string title_reason_discrepancy_uz {
            get {
                return ResourceManager.GetString("title_reason_discrepancy_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Начало аренды.
        /// </summary>
        public static string title_rent_start {
            get {
                return ResourceManager.GetString("title_rent_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возврат.
        /// </summary>
        public static string title_return {
            get {
                return ResourceManager.GetString("title_return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Возврат.
        /// </summary>
        public static string title_return_bit {
            get {
                return ResourceManager.GetString("title_return_bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Род(абр).
        /// </summary>
        public static string title_rod_vag_abbr {
            get {
                return ResourceManager.GetString("title_rod_vag_abbr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Признак маршрута.
        /// </summary>
        public static string title_route {
            get {
                return ResourceManager.GetString("title_route", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маршруты и клиенты.
        /// </summary>
        public static string title_route_client {
            get {
                return ResourceManager.GetString("title_route_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SAP (Входящая поставка).
        /// </summary>
        public static string title_sap_inbound_delivery {
            get {
                return ResourceManager.GetString("title_sap_inbound_delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SAP (Исходящая поставка).
        /// </summary>
        public static string title_sap_outbound_supply {
            get {
                return ResourceManager.GetString("title_sap_outbound_supply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Судно.
        /// </summary>
        public static string title_ship {
            get {
                return ResourceManager.GetString("title_ship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибытие со станции.
        /// </summary>
        public static string title_station_from {
            get {
                return ResourceManager.GetString("title_station_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите станцию прибытия.
        /// </summary>
        public static string title_station_from_invalid {
            get {
                return ResourceManager.GetString("title_station_from_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция назначения.
        /// </summary>
        public static string title_station_name_on {
            get {
                return ResourceManager.GetString("title_station_name_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отправить на станцию АМКР.
        /// </summary>
        public static string title_station_on_amkr {
            get {
                return ResourceManager.GetString("title_station_on_amkr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код.
        /// </summary>
        public static string title_stn_code {
            get {
                return ResourceManager.GetString("title_stn_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название.
        /// </summary>
        public static string title_stn_name {
            get {
                return ResourceManager.GetString("title_stn_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тара (УЗ),т.
        /// </summary>
        public static string title_tara_uz {
            get {
                return ResourceManager.GetString("title_tara_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тариф при выдаче.
        /// </summary>
        public static string title_tariff {
            get {
                return ResourceManager.GetString("title_tariff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Поезда.
        /// </summary>
        public static string title_train {
            get {
                return ResourceManager.GetString("title_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите № поезда.
        /// </summary>
        public static string title_train_invalid {
            get {
                return ResourceManager.GetString("title_train_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Признак собственности.
        /// </summary>
        public static string title_type_ownership {
            get {
                return ResourceManager.GetString("title_type_ownership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип вагона.
        /// </summary>
        public static string title_type_wagons {
            get {
                return ResourceManager.GetString("title_type_wagons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес тары (ут. ЭПД), т.
        /// </summary>
        public static string title_u_tara {
            get {
                return ResourceManager.GetString("title_u_tara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запрет выгр..
        /// </summary>
        public static string title_unloading_ban {
            get {
                return ResourceManager.GetString("title_unloading_ban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип цистерны.
        /// </summary>
        public static string title_usl_tip {
            get {
                return ResourceManager.GetString("title_usl_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Досылочной накладной.
        /// </summary>
        public static string title_uz_doc_num_deliv_doc {
            get {
                return ResourceManager.GetString("title_uz_doc_num_deliv_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Накладной.
        /// </summary>
        public static string title_uz_doc_num_doc {
            get {
                return ResourceManager.GetString("title_uz_doc_num_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер основного документа.
        /// </summary>
        public static string title_uz_doc_num_osn_doc {
            get {
                return ResourceManager.GetString("title_uz_doc_num_osn_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция отправки.
        /// </summary>
        public static string title_uz_route_stn_from {
            get {
                return ResourceManager.GetString("title_uz_route_stn_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция прибытия.
        /// </summary>
        public static string title_uz_route_stn_on {
            get {
                return ResourceManager.GetString("title_uz_route_stn_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагон.
        /// </summary>
        public static string title_vagon {
            get {
                return ResourceManager.GetString("title_vagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акты по вагону.
        /// </summary>
        public static string title_vagon_act {
            get {
                return ResourceManager.GetString("title_vagon_act", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сертификаты и другие документы.
        /// </summary>
        public static string title_vagon_doc {
            get {
                return ResourceManager.GetString("title_vagon_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контроль системной нумерации.
        /// </summary>
        public static string title_validation_num {
            get {
                return ResourceManager.GetString("title_validation_num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес тары (ЭПД), т.
        /// </summary>
        public static string title_ves_tary_arc {
            get {
                return ResourceManager.GetString("title_ves_tary_arc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес тары.
        /// </summary>
        public static string title_ves_tary_uz {
            get {
                return ResourceManager.GetString("title_ves_tary_uz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разница, т.
        /// </summary>
        public static string title_vesg_difference {
            get {
                return ResourceManager.GetString("title_vesg_difference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес груза(накл.), т.
        /// </summary>
        public static string title_vesg_doc {
            get {
                return ResourceManager.GetString("title_vesg_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес груза(перев.), т.
        /// </summary>
        public static string title_vesg_reweighing {
            get {
                return ResourceManager.GetString("title_vesg_reweighing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес груза.
        /// </summary>
        public static string title_vesg_uz_doc {
            get {
                return ResourceManager.GetString("title_vesg_uz_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разметка по прибытию.
        /// </summary>
        public static string title_wagons_condition {
            get {
                return ResourceManager.GetString("title_wagons_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заадресовка.
        /// </summary>
        public static string title_warehouse {
            get {
                return ResourceManager.GetString("title_warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код склада.
        /// </summary>
        public static string title_warehouse_code {
            get {
                return ResourceManager.GetString("title_warehouse_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время.
        /// </summary>
        public static string title_warehouse_date {
            get {
                return ResourceManager.GetString("title_warehouse_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Склад.
        /// </summary>
        public static string title_warehouse_name {
            get {
                return ResourceManager.GetString("title_warehouse_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Переадресация (Заадресовка 10км).
        /// </summary>
        public static string title_warehouse_new {
            get {
                return ResourceManager.GetString("title_warehouse_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Цех.
        /// </summary>
        public static string title_warehouse_shop {
            get {
                return ResourceManager.GetString("title_warehouse_shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Утилиты.
        /// </summary>
        public static string utilite_title {
            get {
                return ResourceManager.GetString("utilite_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номерной учет вагонов, на территории предприятия..
        /// </summary>
        public static string wsd_description {
            get {
                return ResourceManager.GetString("wsd_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на АРМ диспетчера.
        /// </summary>
        public static string wsd_title {
            get {
                return ResourceManager.GetString("wsd_title", resourceCulture);
            }
        }
    }
}
