//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_UI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class IDSRWTResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IDSRWTResource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WEB_UI.App_LocalResources.IDSRWTResource", typeof(IDSRWTResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вагоны АМКР на подходах и станциях УЗ Кривого Рога.
        /// </summary>
        public static string arrival_description {
            get {
                return ResourceManager.GetString("arrival_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подходы.
        /// </summary>
        public static string arrival_title {
            get {
                return ResourceManager.GetString("arrival_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номерной учет по прибытию, прием груза (раскредитация).
        /// </summary>
        public static string incoming_description {
            get {
                return ResourceManager.GetString("incoming_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Принять на АМКР.
        /// </summary>
        public static string incoming_title {
            get {
                return ResourceManager.GetString("incoming_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на «Железнодорожный транспорт АМКР» - внутренняя диспетчерская система оперативного управления перевозочным процессом на железнодорожном транспорте  внутри предприятияПАО «АРСЕЛОРМИТТАЛ КРИВОЙ РОГ».
        /// </summary>
        public static string system_idsrwt_description {
            get {
                return ResourceManager.GetString("system_idsrwt_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВДС «ЖД АМКР».
        /// </summary>
        public static string system_idsrwt_title {
            get {
                return ResourceManager.GetString("system_idsrwt_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Время и дата приема по акту.
        /// </summary>
        public static string title_car_date_adoption_act {
            get {
                return ResourceManager.GetString("title_car_date_adoption_act", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № в поезде.
        /// </summary>
        public static string title_car_position {
            get {
                return ResourceManager.GetString("title_car_position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузоотправитель.
        /// </summary>
        public static string title_client_kod_from {
            get {
                return ResourceManager.GetString("title_client_kod_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузополучатель.
        /// </summary>
        public static string title_client_kod_on {
            get {
                return ResourceManager.GetString("title_client_kod_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коммерческое состояние груза.
        /// </summary>
        public static string title_commercial_condition {
            get {
                return ResourceManager.GetString("title_commercial_condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индекс поезда.
        /// </summary>
        public static string title_composition_index {
            get {
                return ResourceManager.GetString("title_composition_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите индекс поезда.
        /// </summary>
        public static string title_composition_index_invalid {
            get {
                return ResourceManager.GetString("title_composition_index_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата и время прибытия.
        /// </summary>
        public static string title_date_arrival {
            get {
                return ResourceManager.GetString("title_date_arrival", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите дату и время прибытия.
        /// </summary>
        public static string title_date_arrival_invalid {
            get {
                return ResourceManager.GetString("title_date_arrival_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дорога.
        /// </summary>
        public static string title_internal_railroad {
            get {
                return ResourceManager.GetString("title_internal_railroad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Собственник.
        /// </summary>
        public static string title_name_firm_owner {
            get {
                return ResourceManager.GetString("title_name_firm_owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Досылки.
        /// </summary>
        public static string title_nom_dved {
            get {
                return ResourceManager.GetString("title_nom_dved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание.
        /// </summary>
        public static string title_note {
            get {
                return ResourceManager.GetString("title_note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Вагона.
        /// </summary>
        public static string title_num_car {
            get {
                return ResourceManager.GetString("title_num_car", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № ЭПД.
        /// </summary>
        public static string title_num_doc {
            get {
                return ResourceManager.GetString("title_num_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Ревизии.
        /// </summary>
        public static string title_num_rev {
            get {
                return ResourceManager.GetString("title_num_rev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор.
        /// </summary>
        public static string title_operators_wagons {
            get {
                return ResourceManager.GetString("title_operators_wagons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тарифное расстояние.
        /// </summary>
        public static string title_otpr_distance_way {
            get {
                return ResourceManager.GetString("title_otpr_distance_way", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Накладной.
        /// </summary>
        public static string title_otpr_nom_doc {
            get {
                return ResourceManager.GetString("title_otpr_nom_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Платильщик.
        /// </summary>
        public static string title_pl_name_plat {
            get {
                return ResourceManager.GetString("title_pl_name_plat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тариф при выдаче.
        /// </summary>
        public static string title_pl_pay_kod {
            get {
                return ResourceManager.GetString("title_pl_pay_kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата и время перехода погр. пункта.
        /// </summary>
        public static string title_route_joint_cross_time {
            get {
                return ResourceManager.GetString("title_route_joint_cross_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пограничный  пункт.
        /// </summary>
        public static string title_route_joint_stn {
            get {
                return ResourceManager.GetString("title_route_joint_stn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция отправки.
        /// </summary>
        public static string title_route_stn_from {
            get {
                return ResourceManager.GetString("title_route_stn_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Станция прибытия.
        /// </summary>
        public static string title_route_stn_on {
            get {
                return ResourceManager.GetString("title_route_stn_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прибытие со станции.
        /// </summary>
        public static string title_station_from {
            get {
                return ResourceManager.GetString("title_station_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите станцию прибытия.
        /// </summary>
        public static string title_station_from_invalid {
            get {
                return ResourceManager.GetString("title_station_from_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № Поезда.
        /// </summary>
        public static string title_train {
            get {
                return ResourceManager.GetString("title_train", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите № поезда.
        /// </summary>
        public static string title_train_invalid {
            get {
                return ResourceManager.GetString("title_train_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип вагона.
        /// </summary>
        public static string title_type_wagons {
            get {
                return ResourceManager.GetString("title_type_wagons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страна.
        /// </summary>
        public static string title_vagon_adm {
            get {
                return ResourceManager.GetString("title_vagon_adm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Грузоподъемность,т.
        /// </summary>
        public static string title_vagon_gruzp {
            get {
                return ResourceManager.GetString("title_vagon_gruzp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество осей.
        /// </summary>
        public static string title_vagon_kol_os {
            get {
                return ResourceManager.GetString("title_vagon_kol_os", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Род вагона.
        /// </summary>
        public static string title_vagon_rod_vag {
            get {
                return ResourceManager.GetString("title_vagon_rod_vag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес уточ. тары, кг.
        /// </summary>
        public static string title_vagon_u_tara {
            get {
                return ResourceManager.GetString("title_vagon_u_tara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип цистерны.
        /// </summary>
        public static string title_vagon_usl_tip {
            get {
                return ResourceManager.GetString("title_vagon_usl_tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес тары, кг.
        /// </summary>
        public static string title_vagon_ves_tary_arc {
            get {
                return ResourceManager.GetString("title_vagon_ves_tary_arc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код опасного груза.
        /// </summary>
        public static string title_wagon_collect_v_danger_kod {
            get {
                return ResourceManager.GetString("title_wagon_collect_v_danger_kod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название опасного груза.
        /// </summary>
        public static string title_wagon_collect_v_danger_text {
            get {
                return ResourceManager.GetString("title_wagon_collect_v_danger_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код ЕТСНГ.
        /// </summary>
        public static string title_wagon_collect_v_kod_etsng {
            get {
                return ResourceManager.GetString("title_wagon_collect_v_kod_etsng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Код ГНГ.
        /// </summary>
        public static string title_wagon_collect_v_kod_gng {
            get {
                return ResourceManager.GetString("title_wagon_collect_v_kod_gng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол. мест.
        /// </summary>
        public static string title_wagon_collect_v_kol_pac {
            get {
                return ResourceManager.GetString("title_wagon_collect_v_kol_pac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название груза по ЕТСНГ.
        /// </summary>
        public static string title_wagon_collect_v_name_etsng {
            get {
                return ResourceManager.GetString("title_wagon_collect_v_name_etsng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Название груза по ГНГ.
        /// </summary>
        public static string title_wagon_collect_v_name_gng {
            get {
                return ResourceManager.GetString("title_wagon_collect_v_name_gng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вес груза, кг.
        /// </summary>
        public static string title_wagon_collect_v_vesg {
            get {
                return ResourceManager.GetString("title_wagon_collect_v_vesg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № ЗПУ.
        /// </summary>
        public static string title_wagon_zpu_v_nom_zpu {
            get {
                return ResourceManager.GetString("title_wagon_zpu_v_nom_zpu", resourceCulture);
            }
        }
    }
}
