use [KRR-PA-CNT-Railway]

declare @num int = 51175091

--> ОПЕРАЦИИ
--SELECT [id]
--      ,[id_wagon_internal_routes]
--      ,[id_operation]
--      ,[operation_start]
--      ,[operation_end]
--      ,[id_condition]
--      ,[id_loading_status]
--      ,[locomotive1]
--      ,[locomotive2]
--      ,[note]
--      ,[create]
--      ,[create_user]
--      ,[close]
--      ,[close_user]
--      ,[parent_id]
delete
  FROM [IDS].[WagonInternalOperation]
  where [id_wagon_internal_routes] = (select [id] FROM [IDS].[WagonInternalRoutes] where [num] =@num)

--> ДИСЛОКАЦИЯ
--SELECT [id]
--      ,[id_wagon_internal_routes]
--      ,[id_station]
--      ,[id_way]
--      ,[way_start]
--      ,[way_end]
--      ,[id_outer_way]
--      ,[outer_way_start]
--      ,[outer_way_end]
--      ,[position]
--      ,[note]
--      ,[create]
--      ,[create_user]
--      ,[close]
--      ,[close_user]
--      ,[parent_id]
--      ,[id_wio]
--      ,[num_sostav]
delete
  FROM [IDS].[WagonInternalMovement]
  where [id_wagon_internal_routes] = (select [id] FROM [IDS].[WagonInternalRoutes] where [num] =@num)

--SELECT [id]
--      ,[num]
--      ,[id_arrival_car]
--      ,[id_sap_incoming_supply]
--      ,[doc_outgoing_car]
--      ,[id_outgoing_car]
--      ,[id_sap_outbound_supply]
--      ,[note]
--      ,[create]
--      ,[create_user]
--      ,[close]
--      ,[close_user]
--      ,[parent_id]
delete
  FROM [IDS].[WagonInternalRoutes]
  where [num] =@num

--> САП ВХ
--SELECT TOP (1000) [id]
--      ,[id_arrival_car]
--      ,[num]
--      ,[num_doc_uz]
--      ,[date_doc_uz]
--      ,[code_border_checkpoint]
--      ,[name_border_checkpoint]
--      ,[cross_time]
--      ,[VBELN]
--      ,[NUM_VBELN]
--      ,[WERKS]
--      ,[LGORT]
--      ,[LGOBE]
--      ,[ERDAT]
--      ,[ETIME]
--      ,[LGORT_10]
--      ,[LGOBE_10]
--      ,[MATNR]
--      ,[MAKTX]
--      ,[NAME_SH]
--      ,[KOD_R_10]
--      ,[note]
--      ,[term]
--      ,[attempt]
--      ,[create]
--      ,[create_user]
--      ,[change]
--      ,[change_user]
--      ,[close]
--      ,[close_user]
  delete
  FROM [KRR-PA-CNT-Railway].[IDS].[SAPIncomingSupply]
  where [num] =@num

--> ПРИБЫТИЕ
--SELECT [id]
--      ,[id_arrival]
--      ,[num]
--      ,[position]
--      ,[position_arrival]
--      ,[consignee]
--      ,[num_doc]
--      ,[id_transfer]
--      ,[note]
--      ,[date_adoption_act]
--      ,[arrival]
--      ,[arrival_user]
--      ,[create]
--      ,[create_user]
--      ,[change]
--      ,[change_user]
--      ,[id_arrival_uz_vagon]
  delete
  FROM [IDS].[ArrivalCars]
  where [num] =@num
 
--> Документ
--SELECT [id]
--      ,[id_document]
--      ,[num]
--      ,[id_arrival]
--      ,[id_car]
--      ,[id_condition]
--      ,[id_type]
--      ,[gruzp]
--      ,[u_tara]
--      ,[ves_tary_arc]
--      ,[route]
--      ,[note_vagon]
--      ,[id_cargo]
--      ,[id_cargo_gng]
--      ,[id_certification_data]
--      ,[id_commercial_condition]
--      ,[kol_pac]
--      ,[pac]
--      ,[vesg]
--      ,[vesg_reweighing]
--      ,[nom_zpu]
--      ,[danger]
--      ,[danger_kod]
--      ,[cargo_returns]
--      ,[id_station_on_amkr]
--      ,[id_division_on_amkr]
--      ,[empty_car]
--      ,[kol_conductor]
--      ,[create]
--      ,[create_user]
--      ,[change]
--      ,[change_user]
  delete
  FROM [IDS].[Arrival_UZ_Vagon]
  where [num] = @num

--> Спрсвочник
/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
--SELECT [id]
--      ,[num]
--      ,[id_operator]
--      ,[id_limiting]
--      ,[rent_start]
--      ,[rent_end]
--      ,[create]
--      ,[create_user]
--      ,[change]
--      ,[change_user]
--      ,[parent_id]
delete
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_WagonsRent]
  Where [num]=@num

--SELECT [num]
--      ,[id_countrys]
--      ,[id_genus]
--      ,[id_owner]
--      ,[id_operator]
--      ,[change_operator]
--      ,[gruzp]
--      ,[tara]
--      ,[kol_os]
--      ,[usl_tip]
--      ,[date_rem_uz]
--      ,[date_rem_vag]
--      ,[id_type_ownership]
--      ,[sign]
--      ,[factory_number]
--      ,[inventory_number]
--      ,[year_built]
--      ,[exit_ban]
--      ,[note]
--      ,[sobstv_kis]
--      ,[bit_warning]
--      ,[create]
--      ,[create_user]
--      ,[change]
--      ,[change_user]
--      ,[closed_route]
--      ,[new_construction]
delete
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_Wagons]
	Where [num]=@num

