SELECT 
[id_arrival_uz_vagon],
  count([id_arrival_uz_vagon])
  FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars]
  where [create] > '2025-01-01'
  group by [id_arrival_uz_vagon]
  HAVING count([id_arrival_uz_vagon])>1

SELECT TOP (1000) [id]
      ,[id_arrival]
      ,[num]
      ,[position]
      ,[position_arrival]
      ,[consignee]
      ,[num_doc]
      ,[id_transfer]
      ,[note]
      ,[date_adoption_act]
      ,[arrival]
      ,[arrival_user]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[id_arrival_uz_vagon]
  FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars]
	where [id_arrival_uz_vagon] in (SELECT [id_arrival_uz_vagon] FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars] where [create] > '2025-01-01' group by [id_arrival_uz_vagon] HAVING count([id_arrival_uz_vagon])>1)
	order by [id_arrival_uz_vagon]

	SELECT TOP (1000) [id]
      ,[id_document]
      ,[num]
      ,[id_arrival]
      ,[id_car]
      ,[id_condition]
      ,[id_type]
      ,[gruzp]
      ,[u_tara]
      ,[ves_tary_arc]
      ,[route]
      ,[note_vagon]
      ,[id_cargo]
      ,[id_cargo_gng]
      ,[id_certification_data]
      ,[id_commercial_condition]
      ,[kol_pac]
      ,[pac]
      ,[vesg]
      ,[vesg_reweighing]
      ,[nom_zpu]
      ,[danger]
      ,[danger_kod]
      ,[cargo_returns]
      ,[id_station_on_amkr]
      ,[id_division_on_amkr]
      ,[empty_car]
      ,[kol_conductor]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[id_owner]
      ,[id_countrys]
      ,[id_genus]
      ,[kol_os]
      ,[usl_tip]
      ,[date_rem_uz]
      ,[date_rem_vag]
      ,[id_type_ownership]
      ,[gruzp_uz]
      ,[tara_uz]
      ,[zayava]
      ,[manual]
      ,[pay_summa]
      ,[id_wagons_rent_arrival]
      ,[id_act_services1]
      ,[id_act_services2]
      ,[id_act_services3]
      ,[num_act_services1]
      ,[num_act_services2]
      ,[num_act_services3]
      ,[verification]
      ,[verification_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Arrival_UZ_Vagon]
  where [id] in (SELECT [id_arrival_uz_vagon] FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars] where [create] > '2025-01-01' group by [id_arrival_uz_vagon] HAVING count([id_arrival_uz_vagon])>1)
