--UPDATE [IDS].[Arrival_UZ_Vagon]
--   SET [id_document] = 930442
-- WHERE id in (1226299)
--GO



--INSERT INTO [IDS].[Arrival_UZ_Vagon]
--           ([id_document]
--           ,[num]
--           ,[id_arrival]
--           ,[id_car]
--           ,[id_condition]
--           ,[id_type]
--           ,[gruzp]
--           ,[u_tara]
--           ,[ves_tary_arc]
--           ,[route]
--           ,[note_vagon]
--           ,[id_cargo]
--           ,[id_cargo_gng]
--           ,[id_certification_data]
--           ,[id_commercial_condition]
--           ,[kol_pac]
--           ,[pac]
--           ,[vesg]
--           ,[vesg_reweighing]
--           ,[nom_zpu]
--           ,[danger]
--           ,[danger_kod]
--           ,[cargo_returns]
--           ,[id_station_on_amkr]
--           ,[id_division_on_amkr]
--           ,[empty_car]
--           ,[kol_conductor]
--           ,[create]
--           ,[create_user]
--           ,[change]
--           ,[change_user]
--           ,[id_owner]
--           ,[id_countrys]
--           ,[id_genus]
--           ,[kol_os]
--           ,[usl_tip]
--           ,[date_rem_uz]
--           ,[date_rem_vag]
--           ,[id_type_ownership]
--           ,[gruzp_uz]
--           ,[tara_uz]
--           ,[zayava]
--           ,[manual]
--           ,[pay_summa]
--           ,[id_wagons_rent_arrival]
--           ,[id_act_services1]
--           ,[id_act_services2]
--           ,[id_act_services3]
--           ,[num_act_services1]
--           ,[num_act_services2]
--           ,[num_act_services3]
--           ,[verification]
--           ,[verification_user])

--SELECT [id_document] = 931151
--      ,[num]
--      ,[id_arrival] =378177
--      ,[id_car]
--      ,[id_condition]
--      ,[id_type]
--      ,[gruzp]
--      ,[u_tara]
--      ,[ves_tary_arc]
--      ,[route]
--      ,[note_vagon]
--      ,[id_cargo]
--      ,[id_cargo_gng]
--      ,[id_certification_data]
--      ,[id_commercial_condition]
--      ,[kol_pac]
--      ,[pac]
--      ,[vesg]
--      ,[vesg_reweighing]
--      ,[nom_zpu]
--      ,[danger]
--      ,[danger_kod]
--      ,[cargo_returns]
--      ,[id_station_on_amkr]
--      ,[id_division_on_amkr]
--      ,[empty_car]
--      ,[kol_conductor]
--      ,[create]
--      ,[create_user]
--      ,[change]
--      ,[change_user]
--      ,[id_owner]
--      ,[id_countrys]
--      ,[id_genus]
--      ,[kol_os]
--      ,[usl_tip]
--      ,[date_rem_uz]
--      ,[date_rem_vag]
--      ,[id_type_ownership]
--      ,[gruzp_uz]
--      ,[tara_uz]
--      ,[zayava]
--      ,[manual]
--      ,[pay_summa]
--      ,[id_wagons_rent_arrival]
--      ,[id_act_services1]
--      ,[id_act_services2]
--      ,[id_act_services3]
--      ,[num_act_services1]
--      ,[num_act_services2]
--      ,[num_act_services3]
--      ,[verification]
--      ,[verification_user]
--  FROM [KRR-PA-CNT-Railway].[IDS].[Arrival_UZ_Vagon]
--  where id in (1226299)

SELECT TOP (1000) [id]
      ,[id_document]
      ,[num]
      ,[id_arrival]
      ,[id_car]
      ,[id_condition]
      ,[id_type]
      ,[gruzp]
      ,[u_tara]
      ,[ves_tary_arc]
      ,[route]
      ,[note_vagon]
      ,[id_cargo]
      ,[id_cargo_gng]
      ,[id_certification_data]
      ,[id_commercial_condition]
      ,[kol_pac]
      ,[pac]
      ,[vesg]
      ,[vesg_reweighing]
      ,[nom_zpu]
      ,[danger]
      ,[danger_kod]
      ,[cargo_returns]
      ,[id_station_on_amkr]
      ,[id_division_on_amkr]
      ,[empty_car]
      ,[kol_conductor]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[id_owner]
      ,[id_countrys]
      ,[id_genus]
      ,[kol_os]
      ,[usl_tip]
      ,[date_rem_uz]
      ,[date_rem_vag]
      ,[id_type_ownership]
      ,[gruzp_uz]
      ,[tara_uz]
      ,[zayava]
      ,[manual]
      ,[pay_summa]
      ,[id_wagons_rent_arrival]
      ,[id_act_services1]
      ,[id_act_services2]
      ,[id_act_services3]
      ,[num_act_services1]
      ,[num_act_services2]
      ,[num_act_services3]
      ,[verification]
      ,[verification_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Arrival_UZ_Vagon]
  where num in (64226632 )
  order by 1 desc

  SELECT [id]
      ,[id_arrival]
      ,[num]
      ,[position]
      ,[position_arrival]
      ,[consignee]
      ,[num_doc]
      ,[id_transfer]
      ,[note]
      ,[date_adoption_act]
      ,[arrival]
      ,[arrival_user]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[id_arrival_uz_vagon]
  FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars]
  where [id_arrival_uz_vagon] in (select id FROM [KRR-PA-CNT-Railway].[IDS].[Arrival_UZ_Vagon] where num in (64226632  ))
  order by [id_arrival] desc

  SELECT TOP (1000) [id]
      ,[id_doc_uz]
      ,[nom_doc]
      ,[nom_main_doc]
      ,[code_stn_from]
      ,[code_stn_to]
      ,[code_border_checkpoint]
      ,[cross_time]
      ,[code_shipper]
      ,[code_consignee]
      ,[klient]
      ,[code_payer_sender]
      ,[code_payer_arrival]
      ,[distance_way]
      ,[note]
      ,[parent_id]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[manual]
      ,[date_otpr]
      ,[srok_end]
      ,[date_grpol]
      ,[date_pr]
      ,[date_vid]
      ,[code_payer_local]
      ,[tariff_contract]
      ,[calc_payer]
      ,[calc_payer_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Arrival_UZ_Document]
  where id in (931151)  
  
  SELECT TOP (1000) [id]
      ,[id_doc_uz]
      ,[nom_doc]
      ,[nom_main_doc]
      ,[code_stn_from]
      ,[code_stn_to]
      ,[code_border_checkpoint]
      ,[cross_time]
      ,[code_shipper]
      ,[code_consignee]
      ,[klient]
      ,[code_payer_sender]
      ,[code_payer_arrival]
      ,[distance_way]
      ,[note]
      ,[parent_id]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[manual]
      ,[date_otpr]
      ,[srok_end]
      ,[date_grpol]
      ,[date_pr]
      ,[date_vid]
      ,[code_payer_local]
      ,[tariff_contract]
      ,[calc_payer]
      ,[calc_payer_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[Arrival_UZ_Document]
  where [nom_main_doc] in (11384)
  order by 1 desc