use [KRR-PA-CNT-Railway]

declare @num_doc int = 22  
declare @num int = 60397817--61134227--


SELECT [id]
      ,[id_arrived]
      ,[id_sostav]
      ,[train]
      ,[composition_index]
      ,[date_arrival]
      ,[date_adoption]
      ,[date_adoption_act]
      ,[id_station_from]
      ,[id_station_on]
      ,[id_way]
      ,[numeration]
      ,[num_doc]
      ,[count]
      ,[status]
      ,[note]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalSostav]
  where [num_doc] = @num_doc
  order by 1 desc

  declare @id_arrival int = (SELECT TOP (1) [id] FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalSostav] where [num_doc] = @num_doc order by 1 desc)
  
  SELECT [id]
      ,[id_arrival]
      ,[num]
      ,[position]
      ,[position_arrival]
      ,[consignee]
      ,[num_doc]
      ,[id_transfer]
      ,[note]
      ,[date_adoption_act]
      ,[arrival]
      ,[arrival_user]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[id_arrival_uz_vagon]
  FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars]
  where id_arrival = @id_arrival and num = @num--in (64952468,64676331,64067556,64845084,61134227,58901448)

  SELECT [id]
      ,[id_document]
      ,[num]
      --,[id_arrival]
      --,[id_car]
      --,[id_condition]
      --,[id_type]
      --,[gruzp]
      --,[u_tara]
      --,[ves_tary_arc]
      --,[route]
      --,[note_vagon]
      --,[id_cargo]
      --,[id_cargo_gng]
      --,[id_certification_data]
      --,[id_commercial_condition]
      --,[kol_pac]
      --,[pac]
      --,[vesg]
      --,[vesg_reweighing]
      --,[nom_zpu]
      --,[danger]
      --,[danger_kod]
      --,[cargo_returns]
      --,[id_station_on_amkr]
      --,[id_division_on_amkr]
      --,[empty_car]
      --,[kol_conductor]
      --,[create]
      --,[create_user]
      --,[change]
      --,[change_user]
      --,[id_owner]
      --,[id_countrys]
      --,[id_genus]
      --,[kol_os]
      --,[usl_tip]
      --,[date_rem_uz]
      --,[date_rem_vag]
      --,[id_type_ownership]
      --,[gruzp_uz]
      --,[tara_uz]
      --,[zayava]
      --,[manual]
      --,[pay_summa]
      ,[id_wagons_rent_arrival]
  FROM [KRR-PA-CNT-Railway].[IDS].[Arrival_UZ_Vagon]
  where id in (SELECT [id_arrival_uz_vagon] FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars] where id_arrival = @id_arrival and num = @num)

  SELECT rent.[id]
      ,rent.[num]
      ,rent.[id_operator]
	  ,oper.[abbr_ru]
      ,oper.[operators_ru]
      ,oper.[abbr_en]
      ,oper.[operators_en]
      ,rent.[id_limiting]
      ,rent.[rent_start]
      ,rent.[rent_end]
      ,rent.[create]
      ,rent.[create_user]
      ,rent.[change]
      ,rent.[change_user]
      ,rent.[parent_id]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_WagonsRent] as rent
   Left JOIN [IDS].[Directory_OperatorsWagons] as oper ON oper.id = rent.id_operator

  where [num] = @num
  order by 1 desc

