SELECT [num_doc]
      ,[revision]
      ,[status]
      ,[code_from]
      ,[code_on]
      ,[dt]
      ,[xml_doc]
      ,[num_uz]
      ,[close]
      ,[close_message]
  FROM [KRR-PA-CNT-Railway].[IDS].[UZ_DOC]
  where [num_doc] not in (SELECT [num_doc] FROM [KRR-PA-CNT-Railway].[IDS].[ArrivalCars])

SELECT [num_doc]
      ,[revision]
      ,[status]
      ,[code_from]
      ,[code_on]
      ,[dt]
      ,[xml_doc]
      ,[num_uz]
  FROM [KRR-PA-CNT-Railway].[IDS].[UZ_DOC_OUT]
  where [num_doc] not in (SELECT [num_doc] FROM [KRR-PA-CNT-Railway].[IDS].[OutgoingCars])    

SELECT [id]
      ,[id_arrival_car]
      ,[num]
      ,[num_doc_uz]
      ,[date_doc_uz]
      ,[code_border_checkpoint]
      ,[name_border_checkpoint]
      ,[cross_time]
      ,[VBELN]
      ,[NUM_VBELN]
      ,[WERKS]
      ,[LGORT]
      ,[LGOBE]
      ,[ERDAT]
      ,[ETIME]
      ,[LGORT_10]
      ,[LGOBE_10]
      ,[MATNR]
      ,[MAKTX]
      ,[NAME_SH]
      ,[KOD_R_10]
      ,[note]
      ,[term]
      ,[attempt]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[close]
      ,[close_user]
	  --delete
  FROM [KRR-PA-CNT-Railway].[IDS].[SAPIncomingSupply]
  where [id] not in (SELECT [id_sap_incoming_supply] FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalRoutes])

SELECT [id]
      ,[id_out_supply]
      ,[id_outgoing_car]
      ,[num]
      ,[VBELN]
      ,[ERDAT]
      ,[ZBEZEI]
      ,[STAWN]
      ,[NAME1_AG]
      ,[KUNNR_AG]
      ,[ZRWNAME]
      ,[ZENDSTAT]
      ,[ZCRSTNAME]
      ,[ZCROSSSTAT]
      ,[ZZVES_NETTO]
      ,[ABTNR]
      ,[VTEXT]
      ,[ZZDOLG]
      ,[ZZFIO]
      ,[ZZPLATEL]
      ,[ZZNAME_PLATEL]
      ,[note]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[close]
      ,[close_user]
  FROM [KRR-PA-CNT-Railway].[IDS].[SAPOutgoingSupply]
  where [id] not in (SELECT [id_sap_outbound_supply] FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalRoutes])