/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT 
	   out_doc_uz.[id] as id_out_doc_uz
      ,out_doc_uz.[id_doc_uz] as id_out_doc_uz
      ,out_doc_uz.[nom_doc] as out_nom_doc
      ,out_doc_uz.[code_stn_from] as out_code_stn_from
      ,out_doc_uz.[code_stn_to] as out_code_stn_to
      ,out_doc_uz.[country_nazn]
      ,out_doc_uz.[code_border_checkpoint]
      ,out_doc_uz.[cross_date]
      ,out_doc_uz.[code_shipper]
      ,out_doc_uz.[code_consignee]
      ,out_doc_uz.[vid]
      ,out_doc_uz.[code_payer]
      ,out_doc_uz.[distance_way]
      ,out_doc_uz.[osum]
      ,out_doc_uz.[date_sozdan]
      ,out_doc_uz.[date_otpr]
      ,out_doc_uz.[date_pr]
      ,out_doc_uz.[date_grpol]
      ,out_doc_uz.[date_vid]
      ,out_doc_uz.[info_sht]
      ,out_doc_uz.[name_gr]
      ,out_doc_uz.[note]
      ,out_doc_uz.[create]
      ,out_doc_uz.[create_user]
      ,out_doc_uz.[change]
      ,out_doc_uz.[change_user]
	  ,out_vag_uz.[id] as id_out_vag_uz
      ,out_vag_uz.[num]
      ,out_vag_uz.[id_outgoing]
      ,out_vag_uz.[id_car]
      ,out_vag_uz.[id_condition]
      ,out_vag_uz.[id_wagons_rent_arrival]
      ,out_vag_uz.[id_wagons_rent_outgoing]
      ,out_vag_uz.[id_countrys]
      ,out_vag_uz.[id_genus]
      ,out_vag_uz.[id_owner]
      ,out_vag_uz.[gruzp_uz]
      ,out_vag_uz.[tara_uz]
      ,out_vag_uz.[note_uz]
      ,out_vag_uz.[gruzp]
      ,out_vag_uz.[u_tara]
      ,out_vag_uz.[ves_tary_arc]
      ,out_vag_uz.[id_warehouse]
      ,out_vag_uz.[id_division]
      ,out_vag_uz.[laden]
      ,out_vag_uz.[id_cargo]
      ,out_vag_uz.[id_cargo_gng]
      ,out_vag_uz.[vesg]
      ,out_vag_uz.[id_outgoing_detention_return]
      ,out_vag_uz.[create]
      ,out_vag_uz.[create_user]
      ,out_vag_uz.[change]
      ,out_vag_uz.[change_user]
	  ,out_cont_uz.[id] as id_out_cont_uz	  
      ,out_cont_uz.[nom_cont]
      ,out_cont_uz.[kod_tiporazmer]
      ,out_cont_uz.[gruzp]
      ,out_cont_uz.[ves_tary_arc]
      ,out_cont_uz.[id_cargo]
      ,out_cont_uz.[id_cargo_gng]
      ,out_cont_uz.[kol_pac]
      ,out_cont_uz.[pac]
      ,out_cont_uz.[vesg]
      ,[nom_zpu]
  FROM [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Document] as out_doc_uz Right JOIN
  [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon] as out_vag_uz ON out_doc_uz.id = out_vag_uz.id_document left JOIN
  [KRR-PA-CNT-Railway].[IDS].[Outgoing_UZ_Vagon_Cont] as out_cont_uz ON out_vag_uz.id = out_cont_uz.id_vagon