/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT TOP (1000) [id]
      ,[id_document]
      ,[num]
      ,[id_arrival]
      ,[id_car]
      ,[id_condition]
      ,[id_type]
      ,[gruzp]
      ,[u_tara]
      ,[ves_tary_arc]
      ,[route]
      ,[note_vagon]
      ,[id_cargo]
      ,[id_cargo_gng]
      ,[id_certification_data]
      ,[id_commercial_condition]
      ,[kol_pac]
      ,[pac]
      ,[vesg]
      ,[vesg_reweighing]
      ,[nom_zpu]
      ,[danger]
      ,[danger_kod]
      ,[cargo_returns]
      ,[id_station_on_amkr]
      ,[id_division_on_amkr]
      ,[empty_car]
      ,[kol_conductor]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[id_owner]
      ,[id_countrys]
      ,[id_genus]
      ,[kol_os]
      ,[usl_tip]
      ,[date_rem_uz]
      ,[date_rem_vag]
      ,[id_type_ownership]
      ,[gruzp_uz]
      ,[tara_uz]
      ,[zayava]
      ,[manual]
      ,[pay_summa]
  FROM [KRR-PA-CNT-Railway].[IDS].[Arrival_UZ_Vagon]
    where num = 55110274
	/****** Скрипт для команды SelectTopNRows из среды SSMS  ******/
SELECT TOP (1000) [num]
      ,[id_countrys]
      ,[id_genus]
      ,[id_owner]
      ,[id_operator]
      ,[change_operator]
      ,[gruzp]
      ,[tara]
      ,[kol_os]
      ,[usl_tip]
      ,[date_rem_uz]
      ,[date_rem_vag]
      ,[id_type_ownership]
      ,[sign]
      ,[factory_number]
      ,[inventory_number]
      ,[year_built]
      ,[exit_ban]
      ,[note]
      ,[sobstv_kis]
      ,[bit_warning]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[closed_route]
      ,[new_construction]
  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_Wagons]
  where num = 55110274