use [KRR-PA-CNT-Railway]

SELECT 'WagonInternalRoutes - ',  min([create]), max([create]) FROM [IDS].[WagonInternalRoutes]
SELECT 'ArrivalSostav - ',  min([date_arrival]), max([date_arrival]) FROM [IDS].[ArrivalSostav] 
SELECT 'OutgoingSostav - ', min([date_readiness_amkr]), max([date_readiness_amkr]) FROM [IDS].[OutgoingSostav] --group by [date_readiness_amkr] 
SELECT TOP (1000) [id]
      ,[num]
      ,[id_arrival_car]
      ,[id_sap_incoming_supply]
      ,[doc_outgoing_car]
      ,[id_outgoing_car]
      ,[id_sap_outbound_supply]
      ,[note]
      ,[create]
      ,[create_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
  FROM [IDS].[WagonInternalRoutes]
  order by [create]
SELECT TOP (1000) [id]
      ,[id_arrived]
      ,[id_sostav]
      ,[train]
      ,[composition_index]
      ,[date_arrival]
      ,[date_adoption]
      ,[date_adoption_act]
      ,[id_station_from]
      ,[id_station_on]
      ,[id_way]
      ,[numeration]
      ,[num_doc]
      ,[count]
      ,[status]
      ,[note]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
  FROM [IDS].[ArrivalSostav] 
  order by [date_arrival]
SELECT TOP (1000) [id]
      ,[num_doc]
      ,[id_station_from]
      ,[id_way_from]
      ,[id_station_on]
      ,[date_readiness_amkr]
      ,[date_end_inspection_acceptance_delivery]
      ,[date_end_inspection_loader]
      ,[date_end_inspection_vagonnik]
      ,[date_show_wagons]
      ,[date_readiness_uz]
      ,[date_outgoing]
      ,[date_outgoing_act]
      ,[date_departure_amkr]
      ,[composition_index]
      ,[status]
      ,[route_sign]
      ,[note]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[vagonnik_user]
  FROM [IDS].[OutgoingSostav]
  order by [date_readiness_amkr] 




