/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[nom_doc]
      ,[nomer]
      ,[calc_weight]
      ,[etsng_old]
      ,[gng_old]
      ,[gruzp]
      ,[is_removed]
      ,[ostat_davl]
      ,[kod_adm]
      ,[kod_firm_owner]
      ,[kol_conductor]
      ,[kol_os]
      ,[measure_equip_num]
      ,[name_firm_owner]
      ,[negab_do]
      ,[negab_rs]
      ,[negab_v]
      ,[nom_ref]
      ,[pour_off_date]
      ,[pr_sobst]
      ,[pr_zam]
      ,[promoted_by]
      ,[remove_weight]
      ,[rod_vag]
      ,[roller_weight]
      ,[tank_state]
      ,[use]
      ,[usl_tip]
      ,[u_tara]
      ,[ves_tary_arc]
      ,[zd_kod]
      ,[dt]
      ,[flag_railway]
  FROM [KRR-PA-VIZ-Other_DATA].[dbo].[UZ_VagonData]
  where [nomer]='56340847'
  order by 1 desc

/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [id]
      ,[doc_Id]
      ,[doc_Revision]
      ,[doc_Status]
      ,[depart_code]
      ,[arrived_code]
      ,[dt]
      ,[update_dt]
      ,[raw_xml]
      ,[namespace_uri]
  FROM [KRR-PA-VIZ-Other_DATA].[dbo].[UZ_Data]
  where [doc_Id] = '90485730'

  SELECT *  FROM [KRR-PA-VIZ-Other_DATA].[dbo].[UZ_Data] where [doc_Id] in (SELECT [nom_doc] FROM [KRR-PA-VIZ-Other_DATA].[dbo].[UZ_VagonData] where [nomer] = '56340847') and (([depart_code] in (0,7932,'none') and [arrived_code] <> '7932') or ([depart_code]='7932' and [arrived_code] = '7932')) and [doc_Status] in (N'Accepted', N'Delivered', N'Recieved', N'Uncredited') and (dt >= convert(datetime,'2023-11-04 19:20:00',120)) and ((update_dt is not null and update_dt >= convert(datetime,'2023-11-08 19:00:00',120) or (update_dt is null and dt >= convert(datetime,'2023-11-08 19:00:00',120)) or (not ([depart_code]='7932' and [arrived_code]='7932') and update_dt >= convert(datetime,'2023-11-07 19:00:00',120))    )) order by [dt] 