/****** Script for SelectTopNRows command from SSMS  ******/
select * from [IDS].[get_operators_and_genus]()

--SELECT TOP (1000) [id]
--      ,[abbr_ru]
--      ,[operators_ru]
--      ,[abbr_en]
--      ,[operators_en]
--      ,[paid]
--      ,[rop]
--      ,[local_use]
--      ,[color]
--      ,[create]
--      ,[create_user]
--      ,[change]
--      ,[change_user]
--      ,[monitoring_idle_time]
--      ,[parent_id]
--  FROM [KRR-PA-CNT-Railway].[IDS].[Directory_OperatorsWagons]
--  order by [abbr_ru]
