SELECT TOP (1000) [id]
      ,[nom_doc]
      ,[nomer]
      ,[calc_weight]
      ,[etsng_old]
      ,[gng_old]
      ,[gruzp]
      ,[is_removed]
      ,[ostat_davl]
      ,[kod_adm]
      ,[kod_firm_owner]
      ,[kol_conductor]
      ,[kol_os]
      ,[measure_equip_num]
      ,[name_firm_owner]
      ,[negab_do]
      ,[negab_rs]
      ,[negab_v]
      ,[nom_ref]
      ,[pour_off_date]
      ,[pr_sobst]
      ,[pr_zam]
      ,[promoted_by]
      ,[remove_weight]
      ,[rod_vag]
      ,[roller_weight]
      ,[tank_state]
      ,[use]
      ,[usl_tip]
      ,[u_tara]
      ,[ves_tary_arc]
      ,[zd_kod]
      ,[dt]
      ,[flag_railway]
  FROM [KRR-PA-VIZ-Other_DATA].[dbo].[UZ_VagonData]
  where [nomer] = '60931102'
  --where [nomer] = '61627816'
  order by 1 desc

  select * from [dbo].[get_UZ_Data_of_num](60931102) order by[dt] desc
  select * from [dbo].[get_UZ_Data_of_num](61627816) order by[dt] desc