SELECT [id]
      ,[id_operator]
      ,[id_genus]
      ,[start]
      ,[stop]
      ,[id_currency]
      ,[rate]
      ,[id_currency_derailment]
      ,[rate_derailment]
      ,[coefficient_route]
      ,[coefficient_not_route]
      ,[grace_time_1]
      ,[grace_time_2]
      ,[note]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
      ,[hour_after_30]
  FROM [KRR-PA-CNT-Railway-Test].[IDS].[Usage_Fee_Period]
  where [id_operator]=1203 and [id_genus] =22
  order by 1 desc

  SELECT [id]
      ,[id_usage_fee_period]
      ,[code_stn_from]
      ,[id_cargo_arrival]
      ,[code_stn_to]
      ,[id_cargo_outgoing]
      ,[grace_time]
      ,[id_currency]
      ,[rate]
      ,[end_unload]
      ,[start_load]
      ,[id_cargo_group_arrival]
      ,[id_cargo_group_outgoing]
  FROM [KRR-PA-CNT-Railway-Test].[IDS].[Usage_Fee_Period_Detali]
  where [id_usage_fee_period]=2471