SELECT [id]
      ,[id_outgoing]
      ,[num]
      ,[position]
      ,[position_outgoing]
      ,[num_doc]
      ,[note]
      ,[date_outgoing_act]
      ,[outgoing]
      ,[outgoing_user]
      ,[id_outgoing_uz_vagon]
      ,[id_outgoing_detention]
      ,[id_reason_discrepancy_amkr]
      ,[id_reason_discrepancy_uz]
      ,[id_outgoing_return_start]
      ,[id_outgoing_return_stop]
      ,[parent_wir_id]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[note_vagonnik]
      ,[vagonnik]
      ,[vagonnik_user]
  FROM [KRR-PA-CNT-Railway-Test].[IDS].[OutgoingCars]
  where num =64169279
  order by 1 desc
SELECT [id]
      ,[id_outgoing]
      ,[num]
      ,[position]
      ,[position_outgoing]
      ,[num_doc]
      ,[note]
      ,[date_outgoing_act]
      ,[outgoing]
      ,[outgoing_user]
      ,[id_outgoing_uz_vagon]
      ,[id_outgoing_detention]
      ,[id_reason_discrepancy_amkr]
      ,[id_reason_discrepancy_uz]
      ,[id_outgoing_return_start]
      ,[id_outgoing_return_stop]
      ,[parent_wir_id]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[note_vagonnik]
      ,[vagonnik]
      ,[vagonnik_user]
  FROM [KRR-PA-CNT-Railway-Test].[IDS].[OutgoingCars]
  where [id_outgoing] =397931
  order by 1 desc

  SELECT [id]
      ,[num]
      ,[id_operator]
      ,[id_limiting]
      ,[rent_start]
      ,[rent_end]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[parent_id]
  FROM [KRR-PA-CNT-Railway-Test].[IDS].[Directory_WagonsRent]
  where num =64169279
  order by 1 desc
