SELECT TOP (1000) [id]
      ,[id_wagon_internal_routes]
      ,[id_operation]
      ,[operation_start]
      ,[operation_end]
      ,[id_condition]
      ,[id_loading_status]
      ,[locomotive1]
      ,[locomotive2]
      ,[note]
      ,[create]
      ,[create_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
      ,[con_change]
      ,[con_change_user]
      ,[id_organization_service]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalOperation]
  where [close] is null and id_loading_status = 0 and [id_operation] <> 15 and [id_operation] <> 16

SELECT TOP (1000) [id]
      ,[id_wagon_internal_routes]
      ,[internal_doc_num]
      ,[id_weighing_num]
      ,[doc_received]
      ,[id_cargo]
      ,[id_internal_cargo]
      ,[empty]
      ,[vesg]
      ,[id_station_from_amkr]
      ,[id_division_from]
      ,[id_wim_load]
      ,[id_wim_redirection]
      ,[code_external_station]
      ,[id_station_on_amkr]
      ,[id_division_on]
      ,[create]
      ,[create_user]
      ,[change]
      ,[change_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalMoveCargo]
  where [id_wagon_internal_routes] in (select [id_wagon_internal_routes] FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalOperation]
  where [close] is null and id_loading_status = 0 and [id_operation] <> 15 and [id_operation] <> 16) 
  and [close] is null and not (([id_cargo] = 1 and [id_internal_cargo] is null) or ([id_cargo] is null and [id_internal_cargo] = 0 ))
  --order by 1 desc
