SELECT TOP (1000) [id]
      ,[id_wagon_internal_routes]
      ,[id_station]
      ,[id_way]
      ,[way_start]
      ,[way_end]
      ,[id_outer_way]
      ,[outer_way_start]
      ,[outer_way_end]
      ,[position]
      ,[note]
      ,[create]
      ,[create_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
      ,[id_wio]
      ,[num_sostav]
      ,[filing_start]
      ,[filing_end]
      ,[id_filing]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalMovement]
  where id in (SELECT [id_wim_load]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalMoveCargo]
  group by [id_wim_load]
  HAVING count([id_wim_load]) > 1)
  order by [id_filing]

  SELECT TOP (1000) [id]
      ,[num]
      ,[id_arrival_car]
      ,[id_sap_incoming_supply]
      ,[doc_outgoing_car]
      ,[id_outgoing_car]
      ,[id_sap_outbound_supply]
      ,[note]
      ,[create]
      ,[create_user]
      ,[close]
      ,[close_user]
      ,[parent_id]
      ,[highlight_color]
      ,[id_usage_fee]
      ,[note2]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalRoutes]
  where [id] in (select [id_wagon_internal_routes] FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalMovement]
  where id in (SELECT [id_wim_load]
  FROM [KRR-PA-CNT-Railway].[IDS].[WagonInternalMoveCargo]
  group by [id_wim_load]
  HAVING count([id_wim_load]) > 1))
